Repository phel-lang/phel-lang, pull requests merged in 2020-12, with the labels that each got.

#131 Add some rules related to phpdoc
  .php_cs.dist
  src/php/Compiler/Analyzer/TupleSymbol/InvokeSymbol.php
  src/php/Compiler/Analyzer/TupleSymbol/LetSymbol.php
  src/php/Compiler/Analyzer/TupleSymbol/LoopSymbol.php
  src/php/Compiler/Analyzer/TupleSymbol/NsSymbol.php
  src/php/Compiler/Analyzer/TupleSymbol/ReadModel/FnSymbolTuple.php
  src/php/Compiler/Analyzer/TupleSymbol/TrySymbol.php
  src/php/Compiler/Emitter.php
  src/php/Compiler/Emitter/EvalEmitter.php
  src/php/Compiler/Emitter/EvalEmitterInterface.php
  src/php/Compiler/Emitter/OutputEmitter/Munge.php
  src/php/Compiler/EmitterInterface.php
  src/php/Compiler/EvalCompiler.php
  src/php/Compiler/EvalCompilerInterface.php
  src/php/Compiler/NodeEnvironment.php
  src/php/Compiler/Reader.php
  src/php/Lang/Tuple.php
  tests/php/Unit/Compiler/Analyzer/TupleSymbol/FnSymbolTest.php
  tests/php/Unit/Compiler/ReaderTest.php
Labels: documentation

#133 Creating runtime module
  composer.lock
  doc/build-api-page.php
  doc/content/documentation/configuration.md
  src/phel/test.phel
  src/php/Command/CommandFactory.php
  src/php/Command/CommandFactoryInterface.php
  src/php/Command/RunCommand.php
  src/php/Command/TestCommand.php
  src/php/Compiler/Emitter/OutputEmitter/NodeEmitter/NsEmitter.php
  src/php/Compiler/Emitter/OutputEmitter/SourceMap/VLQ.php
  src/php/Main.php
  src/php/Runtime/Runtime.php
  src/php/Runtime/RuntimeFactory.php
  src/php/Runtime/RuntimeInterface.php
  tests/php/Integration/Command/RunCommandTest.php
  tests/php/Integration/Command/TestCommandTest.php
  tests/php/Integration/Fixtures/Def/namespace-def.test
  tests/php/Integration/Fixtures/Let/loop-destructure.test
  tests/php/Integration/Fixtures/New/new-from-alias.test
  tests/php/Integration/Fixtures/Ns/munge-ns.test
  tests/php/Integration/Fixtures/Ns/require.test
  tests/php/Integration/Fixtures/Ns/use.test
  tests/php/Integration/IntegrationTest.php
  tests/php/Unit/Runtime/RuntimeMock.php
  tests/php/Unit/Runtime/RuntimeTest.php
Labels: refactoring

#124 Adding ADRs to the project
  .github/PULL_REQUEST_TEMPLATE.md
  Readme.md
  adrs/0000_adr_template.md
Labels: documentation

#134 Refactor Printer
  composer.json
  src/php/Printer.php
  src/php/Printer/ArrayPrinter.php
  src/php/Printer/BooleanPrinter.php
  src/php/Printer/KeywordPrinter.php
  src/php/Printer/NullPrinter.php
  src/php/Printer/NumericalPrinter.php
  src/php/Printer/ObjectPrinter.php
  src/php/Printer/PhelArrayPrinter.php
  src/php/Printer/PrinterInterface.php
  src/php/Printer/ResourcePrinter.php
  src/php/Printer/SetPrinter.php
  src/php/Printer/StringPrinter.php
  src/php/Printer/StructPrinter.php
  src/php/Printer/SymbolPrinter.php
  src/php/Printer/TablePrinter.php
  src/php/Printer/TuplePrinter.php
Labels: refactoring

#139 Add csrun in test-all & simplify zola documentation
  Readme.md
Labels: documentation

#138 Modularize printer component
  .gitignore
  composer.json
  composer.lock
  phpunit.xml.dist
  src/phel/core.phel
  src/php/Command/ReplCommand.php
  src/php/Compiler/Emitter/OutputEmitter/LiteralEmitter.php
  src/php/Exceptions/HtmlExceptionPrinter.php
  src/php/Exceptions/TextExceptionPrinter.php
  src/php/Lang/Keyword.php
  src/php/Lang/PhelArray.php
  src/php/Lang/Set.php
  src/php/Lang/Struct.php
  src/php/Lang/Symbol.php
  src/php/Lang/Table.php
  src/php/Lang/Tuple.php
  src/php/Printer/Printer.php
  src/php/Printer/TypePrinter/ArrayPrinter.php
  src/php/Printer/TypePrinter/BooleanPrinter.php
  src/php/Printer/TypePrinter/KeywordPrinter.php
  src/php/Printer/TypePrinter/NullPrinter.php
  src/php/Printer/TypePrinter/NumberPrinter.php
  src/php/Printer/TypePrinter/ObjectPrinter.php
  src/php/Printer/TypePrinter/PhelArrayPrinter.php
  src/php/Printer/TypePrinter/ResourcePrinter.php
  src/php/Printer/TypePrinter/SetPrinter.php
  src/php/Printer/TypePrinter/StringPrinter.php
  src/php/Printer/TypePrinter/StructPrinter.php
  src/php/Printer/TypePrinter/SymbolPrinter.php
  src/php/Printer/TypePrinter/TablePrinter.php
  src/php/Printer/TypePrinter/TuplePrinter.php
  src/php/Printer/TypePrinter/TypePrinterInterface.php
  tests/php/Unit/Lang/FakeStruct.php
  tests/php/Unit/Lang/StructTest.php
  tests/php/Unit/Printer/PrinterTest.php
  tests/php/Unit/Printer/TypePrinter/ArrayPrinterTest.php
  tests/php/Unit/Printer/TypePrinter/BooleanPrinterTest.php
  tests/php/Unit/Printer/TypePrinter/KeywordPrinterTest.php
  tests/php/Unit/Printer/TypePrinter/NullPrinterTest.php
  tests/php/Unit/Printer/TypePrinter/NumberPrinterTest.php
  tests/php/Unit/Printer/TypePrinter/ObjectPrinterTest.php
  tests/php/Unit/Printer/TypePrinter/PhelArrayPrinterTest.php
  tests/php/Unit/Printer/TypePrinter/ResourcePrinterTest.php
  tests/php/Unit/Printer/TypePrinter/SetPrinterTest.php
  tests/php/Unit/Printer/TypePrinter/StringPrinterTest.php
  tests/php/Unit/Printer/TypePrinter/StructPrinterTest.php
  tests/php/Unit/Printer/TypePrinter/StubStruct.php
  tests/php/Unit/Printer/TypePrinter/SymbolPrinterTest.php
  tests/php/Unit/Printer/TypePrinter/TablePrinterTest.php
  tests/php/Unit/Printer/TypePrinter/TuplePrinterTest.php
Labels: refactoring

#141 Rename Main to PhelFacade
  phel
  src/php/PhelFacade.php
Labels: refactoring

#136 Adds test for post with form data.
  src/phel/http.phel
  tests/phel/test/http.phel
Labels: Pure testing

#144 Adding var-dumper as require-dev dependency
  composer.json
  composer.lock
Labels: enhancement

#143 Refactor Destructure class
  src/php/Compiler/Analyzer/AnalyzeTuple.php
  src/php/Compiler/Analyzer/TupleSymbol/Binding/BindingValidator.php
  src/php/Compiler/Analyzer/TupleSymbol/Binding/BindingValidatorInterface.php
  src/php/Compiler/Analyzer/TupleSymbol/Binding/Deconstructor/BindingDeconstructorInterface.php
  src/php/Compiler/Analyzer/TupleSymbol/Binding/Deconstructor/NullBindingDeconstructor.php
  src/php/Compiler/Analyzer/TupleSymbol/Binding/Deconstructor/PhelArrayBindingDeconstructor.php
  src/php/Compiler/Analyzer/TupleSymbol/Binding/Deconstructor/SymbolBindingDeconstructor.php
  src/php/Compiler/Analyzer/TupleSymbol/Binding/Deconstructor/TableBindingDeconstructor.php
  src/php/Compiler/Analyzer/TupleSymbol/Binding/Deconstructor/TupleBindingDeconstructor.php
  src/php/Compiler/Analyzer/TupleSymbol/Binding/TupleDeconstructor.php
  src/php/Compiler/Analyzer/TupleSymbol/Binding/TupleDeconstructorInterface.php
  src/php/Compiler/Analyzer/TupleSymbol/LetSymbol.php
  src/php/Compiler/Analyzer/TupleSymbol/LoopSymbol.php
  src/php/Destructure.php
  tests/php/Unit/Compiler/Analyzer/TupleSymbol/Binding/BindingValidatorTest.php
  tests/php/Unit/Compiler/Analyzer/TupleSymbol/Binding/Deconstructor/PhelArrayBindingDeconstructorTest.php
  tests/php/Unit/Compiler/Analyzer/TupleSymbol/Binding/Deconstructor/SymbolBindingDeconstructorTest.php
  tests/php/Unit/Compiler/Analyzer/TupleSymbol/Binding/Deconstructor/TableBindingDeconstructorTest.php
  tests/php/Unit/Compiler/Analyzer/TupleSymbol/Binding/Deconstructor/TupleBindingDeconstructorTest.php
  tests/php/Unit/Compiler/Analyzer/TupleSymbol/Binding/TupleDeconstructorTest.php
  tests/php/Unit/Compiler/Analyzer/TupleSymbol/LetSymbolTest.php
  tests/php/Unit/Compiler/Analyzer/TupleSymbol/LoopSymbolTest.php
Labels: refactoring
