Repository phel-lang/phel-lang, pull requests merged in 2021-09, with the labels that each got.

#340 Update Dependencies
  composer.json
  composer.lock
Labels: dependencies

#332 Allow Gacela php config
  .gitignore
  composer.json
  gacela.php
  phel-config.php
  src/php/AbstractPhelConfig.php
  src/php/Command/CommandConfig.php
  src/php/Config/ExportConfiguration.php
  src/php/Config/ProjectConfiguration.php
  src/php/Config/TestConfiguration.php
  src/php/Interop/InteropConfig.php
  tests/php/Integration/Command/Export/composer.json
  tests/php/Integration/Command/Export/config/default.php
  tests/php/Integration/Command/Test/composer.json
  tests/php/Integration/Command/Test/config/default.php
Labels: enhancement

#342 Load replStartupFile on ReplCommand->execute()
  src/php/Command/CommandConfig.php
  src/php/Command/CommandFactory.php
  src/php/Command/Repl/ReplCommand.php
Labels: bug

#343 Using arg unpacking in config dirs setters
  phel-config.php
  src/php/Config/ExportConfiguration.php
  src/php/Config/TestConfiguration.php
Labels: refactoring

#345 Use raw arrays for config
  phel-config.php
  src/php/Command/CommandConfig.php
  src/php/Config/ExportConfiguration.php
  src/php/Config/ProjectConfiguration.php
  src/php/Config/TestConfiguration.php
  tests/php/Integration/Command/Export/config/default.php
  tests/php/Integration/Command/Test/config/default.php
Labels: refactoring

#347 Refactor BuildFacade; extract to classes the logic from the facade
  src/php/Build/BuildFacade.php
  src/php/Build/BuildFacadeInterface.php
  src/php/Build/BuildFactory.php
  src/php/Build/Compile/CompiledFile.php
  src/php/Build/Compile/DependenciesForNamespace.php
  src/php/Build/Compile/FileCompiler.php
  src/php/Build/Compile/FileEvaluator.php
  src/php/Build/Compile/ProjectCompiler.php
  src/php/Build/Extractor/NamespaceExtractor.php
Labels: refactoring

#346 Create RuntimeCommand and remove phel-composer-plugin dependency
  .github/workflows/ci.yml
  composer.json
  composer.lock
  phel
  phel-config.php
  src/php/Command/CommandConfig.php
  src/php/Command/CommandFacade.php
  src/php/Command/CommandFactory.php
  src/php/Command/Runtime/ConfigNormalizer.php
  src/php/Command/Runtime/RuntimeCommand.php
  src/php/Command/Runtime/RuntimeFileGenerator.php
  src/php/Command/Test/TestCommand.php
  tests/php/Unit/Command/Runtime/ConfigNormalizerTest.php
  tests/php/Unit/Command/Runtime/RuntimeFileGeneratorTest.php
Labels: enhancement

#352 Use phel-test as a prefix for tests/phel directory
  phel-config.php
  tests/phel/test/core.phel
  tests/phel/test/core/basic-constructors.phel
  tests/phel/test/core/basic-sequence-operation.phel
  tests/phel/test/core/bitwise-operation.phel
  tests/phel/test/core/boolean-operation.phel
  tests/phel/test/core/control-structures.phel
  tests/phel/test/core/for-loop.phel
  tests/phel/test/core/function-operation.phel
  tests/phel/test/core/math-operation.phel
  tests/phel/test/core/more-sequence-operation.phel
  tests/phel/test/core/print-operation.phel
  tests/phel/test/core/regex-functions.phel
  tests/phel/test/core/sequence-functions.phel
  tests/phel/test/core/sequence-operation.phel
  tests/phel/test/core/set-operation.phel
  tests/phel/test/core/threading-macros.phel
  tests/phel/test/core/type-operation.phel
  tests/phel/test/html.phel
  tests/phel/test/http.phel
  tests/phel/test/special-forms.phel
Labels: refactoring

#354 Move ExportCommand inside Interop module
  phel
  src/php/Command/CommandFacade.php
  src/php/Command/CommandFacadeInterface.php
  src/php/Command/CommandFactory.php
  src/php/Command/Export/ExportCommand.php
  src/php/Interop/Command/ExportCommand.php
  src/php/Interop/InteropDependencyProvider.php
  src/php/Interop/InteropFacade.php
  src/php/Interop/InteropFacadeInterface.php
  src/php/Interop/InteropFactory.php
  tests/php/Integration/Interop/Command/Export/ExportCommandTest.php
  tests/php/Integration/Interop/Command/Export/config/phel-config.php
  tests/php/Integration/Interop/Command/Export/src/test-cmd-export-multiple/adder.phel
  tests/php/Integration/Interop/Command/Export/src/test-cmd-export-multiple/multiplier.phel
Labels: refactoring

#355 Move FormatCommand inside Formatter module
  phel
  src/php/Command/CommandFacade.php
  src/php/Command/CommandFactory.php
  src/php/Formatter/Command/FormatCommand.php
  src/php/Formatter/Command/PathFilterInterface.php
  src/php/Formatter/Command/PhelPathFilter.php
  src/php/Formatter/FormatterDependencyProvider.php
  src/php/Formatter/FormatterFacade.php
  src/php/Formatter/FormatterFacadeInterface.php
  src/php/Formatter/FormatterFactory.php
  tests/php/Integration/Command/Format/vendor/PhelRuntime.php
  tests/php/Integration/Formatter/Command/Format/Fixtures/bad-format.phel
  tests/php/Integration/Formatter/Command/Format/Fixtures/good-format.phel
  tests/php/Integration/Formatter/Command/Format/FormatCommandTest.php
Labels: refactoring

#358 Use Exceptions from the Command module
  src/phel/test.phel
  src/php/Command/CommandFactory.php
  src/php/Command/Shared/CommandExceptionWriter.php
  src/php/Command/Shared/Exceptions/Extractor/FilePositionExtractor.php
  src/php/Command/Shared/Exceptions/Extractor/FilePositionExtractorInterface.php
  src/php/Command/Shared/Exceptions/Extractor/SourceMapExtractor.php
  src/php/Command/Shared/Exceptions/Extractor/SourceMapExtractorInterface.php
  src/php/Command/Shared/Exceptions/TextExceptionPrinter.php
  src/php/Runtime/Exceptions/ExceptionArgsPrinter.php
  src/php/Runtime/Exceptions/ExceptionArgsPrinterInterface.php
  src/php/Runtime/Exceptions/ExceptionPrinterInterface.php
  src/php/Runtime/Exceptions/Extractor/FilePositionExtractor.php
  src/php/Runtime/Exceptions/Extractor/FilePositionExtractorInterface.php
  src/php/Runtime/Exceptions/Extractor/ReadModel/FilePosition.php
  src/php/Runtime/Exceptions/Extractor/ReadModel/SourceMapInformation.php
  src/php/Runtime/Exceptions/Extractor/SourceMapExtractor.php
  src/php/Runtime/Exceptions/Extractor/SourceMapExtractorInterface.php
  src/php/Runtime/Exceptions/HtmlExceptionPrinter.php
  src/php/Runtime/Exceptions/PhelRuntimeException.php
  src/php/Runtime/Exceptions/TextExceptionPrinter.php
  tests/php/Integration/Run/Command/Repl/ReplCommandTest.php
  tests/php/Integration/Run/Command/Repl/ReplTestIo.php
  tests/php/Unit/Exceptions/Extractor/FilePositionExtractorTest.php
  tests/php/Unit/Exceptions/Printer/ExceptionArgsPrinterTest.php
  tests/php/Unit/Exceptions/TextExceptionPrinterTest.php
Labels: refactoring
