Repository phel-lang/phel-lang, pull requests merged in 2021-01, with the labels that each got.

#148 Introducing parser factory
  src/php/Compiler/CompilerFactory.php
  src/php/Compiler/Parser.php
  src/php/Compiler/Parser/ExpressionParser/ListParser.php
  src/php/Compiler/Parser/ExpressionParser/StringParser.php
  src/php/Compiler/Parser/ExpressionParserFactory.php
  src/php/Compiler/Parser/ExpressionParserFactoryInterface.php
  src/php/Compiler/Parser/ExpressionReaderFactory.php
  src/php/Compiler/Parser/ExpressionReaderFactoryInterface.php
  src/php/Compiler/Parser/ParserNode/CommentNode.php
  src/php/Compiler/Parser/ParserNode/NewlineNode.php
  src/php/Compiler/Parser/ParserNode/WhitespaceNode.php
  src/php/Compiler/Reader.php
  tests/php/Integration/IntegrationTest.php
  tests/php/Unit/Compiler/LexerTest.php
  tests/php/Unit/Compiler/ParseAndPrintTest.php
  tests/php/Unit/Compiler/ParserTest.php
  tests/php/Unit/Compiler/ReaderTest.php
  tests/php/Unit/Printer/PrinterTest.php
Labels: refactoring

#149 Created CommandFacade
  phel
  src/php/Command/CommandFacade.php
  src/php/Command/CommandFacadeInterface.php
  src/php/PhelFacade.php
Labels: refactoring

#157 Implementing rand-nth
  doc/content/documentation/api.md
  src/phel/core.phel
Labels: enhancement

#159 Implement str-contains? in phel
  doc/content/documentation/api.md
  src/phel/core.phel
  tests/phel/test/core.phel
Labels: enhancement

#164 Fixes typo.
  doc/content/documentation/array-table-and-struct.md
Labels: documentation

#162 Adding argv to the core
  doc/content/documentation/api.md
  src/phel/core.phel
Labels: enhancement

#163 Refactor FnAsClassEmitter
  src/php/Compiler/Analyzer/Ast/PhpVarNode.php
  src/php/Compiler/Emitter/OutputEmitter/NodeEmitter/FnAsClassEmitter.php
  tests/php/Unit/Compiler/Emitter/OutputEmitter/NodeEmitter/FnAsClassEmitterTest.php
Labels: refactoring

#167 Fix Printer (object types)
  src/php/Printer/Printer.php
Labels: bug

#166 Adding scrutinizer to the readme
  Readme.md
Labels: documentation, enhancement

#170 Remove array_merge from loop
  src/php/Command/Shared/NamespaceExtractor.php
Labels: good first issue, refactoring

#172 Refactor StringPrinter class
  src/php/Printer/TypePrinter/StringPrinter.php
Labels: refactoring

#171 Added format + printf phel functions
  doc/content/documentation/api.md
  src/phel/core.phel
  tests/phel/test/core.phel
Labels: enhancement

#177 Rename php.dockerfile to Dockerfile
  build/Dockerfile
  docker-compose.yml
Labels: good first issue

#178 Adding unit tests to TextExceptionPrinter
  src/php/Command/CommandFactory.php
  src/php/Command/Repl/ColorStyle.php
  src/php/Command/Repl/ColorStyleInterface.php
  src/php/Compiler/Emitter/OutputEmitter/Munge.php
  src/php/Compiler/Emitter/OutputEmitter/MungeInterface.php
  src/php/Compiler/Emitter/OutputEmitter/SourceMap/SourceMapConsumer.php
  src/php/Exceptions/Extractor/FilePositionExtractor.php
  src/php/Exceptions/Extractor/FilePositionExtractorInterface.php
  src/php/Exceptions/Extractor/ReadModel/FilePosition.php
  src/php/Exceptions/Extractor/ReadModel/SourceMapInformation.php
  src/php/Exceptions/Extractor/SourceMapExtractor.php
  src/php/Exceptions/Extractor/SourceMapExtractorInterface.php
  src/php/Exceptions/HtmlExceptionPrinter.php
  src/php/Exceptions/Printer/ExceptionArgsPrinter.php
  src/php/Exceptions/Printer/ExceptionArgsPrinterInterface.php
  src/php/Exceptions/TextExceptionPrinter.php
  src/php/Printer/Printer.php
  src/php/Printer/PrinterInterface.php
  src/php/Runtime/RuntimeFactory.php
  tests/php/Unit/Exceptions/Extractor/FilePositionExtractorTest.php
  tests/php/Unit/Exceptions/TextExceptionPrinterTest.php
Labels: refactoring

#182 Installing phpmetrics in require-dev
  composer.json
  composer.lock
Labels: enhancement

#180 Clean up ParserNodes
  .github/workflows/ci.yml
  .php_cs.dist
  composer.json
  src/php/Compiler/Parser/ParserNode/AbstractAtomNode.php
  src/php/Compiler/Parser/ParserNode/BooleanNode.php
  src/php/Compiler/Parser/ParserNode/CommentNode.php
  src/php/Compiler/Parser/ParserNode/FileNode.php
  src/php/Compiler/Parser/ParserNode/InnerNodeInterface.php
  src/php/Compiler/Parser/ParserNode/KeywordNode.php
  src/php/Compiler/Parser/ParserNode/ListNode.php
  src/php/Compiler/Parser/ParserNode/MetaNode.php
  src/php/Compiler/Parser/ParserNode/NewlineNode.php
  src/php/Compiler/Parser/ParserNode/NilNode.php
  src/php/Compiler/Parser/ParserNode/NodeInterface.php
  src/php/Compiler/Parser/ParserNode/NumberNode.php
  src/php/Compiler/Parser/ParserNode/QuoteNode.php
  src/php/Compiler/Parser/ParserNode/StringNode.php
  src/php/Compiler/Parser/ParserNode/SymbolNode.php
  src/php/Compiler/Parser/ParserNode/TriviaNodeInterface.php
  src/php/Compiler/Parser/ParserNode/WhitespaceNode.php
Labels: refactoring

#188 Fix errors from the printers + catch potential error in repl
  phel
  src/php/Command/ReplCommand.php
  src/php/Exceptions/HtmlExceptionPrinter.php
  src/php/Exceptions/TextExceptionPrinter.php
Labels: enhancement

#190 Refactoring Formatter module: adding FormatterFactory
  phel
  src/php/Command/CommandFactory.php
  src/php/Command/FormatCommand.php
  src/php/Formatter/AbstractZipper.php
  src/php/Formatter/Formatter.php
  src/php/Formatter/FormatterFactory.php
  src/php/Formatter/FormatterFactoryInterface.php
  src/php/Formatter/FormatterInterface.php
  src/php/Formatter/ParseTreeZipper.php
  src/php/Formatter/Rules/IndentRule.php
  src/php/Formatter/Rules/Indenter/BlockIndenter.php
  src/php/Formatter/Rules/Indenter/InnerIndenter.php
  src/php/Formatter/Rules/Indenter/LineIndenter.php
  src/php/Formatter/Rules/Indenter/ListIndenter.php
  src/php/Formatter/Rules/RemoveSurroundingWhitespaceRule.php
  src/php/Formatter/Rules/RemoveTrailingWhitespaceRule.php
  src/php/Formatter/Rules/UnindentRule.php
  tests/php/Integration/Command/RunCommandTest.php
  tests/php/Integration/Command/TestCommandTest.php
  tests/php/Unit/Formatter/ArrayZipper.php
  tests/php/Unit/Formatter/Rules/IndentRuleTest.php
  tests/php/Unit/Formatter/Rules/RemoveSurroundingWhitespaceRuleTest.php
  tests/php/Unit/Formatter/Rules/RemoveTrailingWhitespaceRuleTest.php
  tests/php/Unit/Formatter/Rules/RuleParserTrait.php
  tests/php/Unit/Formatter/Rules/UnindentRuleTest.php
  tests/php/Unit/Formatter/ZipperTest.php
Labels: refactoring

#199 Improve FormatCommand
  src/php/Command/CommandFacade.php
  src/php/Command/CommandFacadeInterface.php
  src/php/Command/CommandFactory.php
  src/php/Command/Format/PathFilterInterface.php
  src/php/Command/Format/PhelPathFilter.php
  src/php/Command/FormatCommand.php
  src/php/Command/Shared/CommandIoInterface.php
  src/php/Command/Shared/CommandSystemIo.php
  src/php/Formatter/Formatter.php
  src/php/Formatter/FormatterInterface.php
  src/php/PhelFacade.php
  tests/php/Integration/Command/Fixtures/test-fmt/bad-format.phel
  tests/php/Integration/Command/Fixtures/test-fmt/good-format.phel
  tests/php/Integration/Command/FormatCommandTest.php
Labels: enhancement

#191 Allow multiline REPL expressions
  src/php/Command/CommandFactory.php
  src/php/Command/ReplCommand.php
  src/php/Compiler/EvalCompiler.php
  src/php/Compiler/EvalCompilerInterface.php
  src/php/Compiler/Parser/ExpressionParser/ListParser.php
  src/php/Compiler/Parser/Parser.php
  src/php/Exceptions/Parser/UnexpectedParserException.php
  src/php/Exceptions/Parser/UnfinishedParserException.php
  src/php/Exceptions/ParserException.php
  tests/php/Integration/Repl/Fixtures/unexpected-token.test
  tests/php/Integration/Repl/Fixtures/unterminated-list.test
  tests/php/Integration/Repl/ReplIntegrationTest.php
Labels: enhancement

#200 Statement number in REPL
  src/php/Command/Repl/ReplCommandIoInterface.php
  src/php/Command/Repl/ReplCommandSystemIo.php
  src/php/Command/ReplCommand.php
  src/php/Compiler/EvalCompiler.php
  src/php/Compiler/EvalCompilerInterface.php
  src/php/Compiler/Lexer/Lexer.php
  src/php/Compiler/Lexer/LexerInterface.php
  src/php/Compiler/Parser/Parser.php
  src/php/Compiler/Parser/ParserInterface.php
  src/php/Exceptions/TextExceptionPrinter.php
  tests/php/Integration/Repl/Fixtures/simple-add-multiline.test
  tests/php/Integration/Repl/Fixtures/simple-add.test
  tests/php/Integration/Repl/Fixtures/unexpected-token.test
  tests/php/Integration/Repl/Fixtures/unterminated-list-multiline.test
  tests/php/Integration/Repl/ReplIntegrationTest.php
  tests/php/Integration/Repl/ReplTestIo.php
Labels: enhancement

#202 Basic colors to repl printers
  src/phel/repl.phel
  src/phel/test.phel
  src/php/Command/CommandFactory.php
  src/php/Command/Repl/startup.phel
  src/php/Compiler/CompilerFactory.php
  src/php/Compiler/Emitter/OutputEmitter.php
  src/php/Compiler/Emitter/OutputEmitter/LiteralEmitter.php
  src/php/Printer/Printer.php
  src/php/Printer/TypePrinter/BooleanPrinter.php
  src/php/Printer/TypePrinter/KeywordPrinter.php
  src/php/Printer/TypePrinter/NullPrinter.php
  src/php/Printer/TypePrinter/NumberPrinter.php
  src/php/Printer/TypePrinter/PhelArrayPrinter.php
  src/php/Printer/TypePrinter/SetPrinter.php
  src/php/Printer/TypePrinter/StringPrinter.php
  src/php/Printer/TypePrinter/StructPrinter.php
  src/php/Printer/TypePrinter/SymbolPrinter.php
  src/php/Printer/TypePrinter/TablePrinter.php
  src/php/Printer/TypePrinter/TuplePrinter.php
Labels: enhancement

#207 Save in history incorrect REPL expressions
  src/php/Command/ReplCommand.php
Labels: enhancement

#212 Fix comparing arrays
  src/php/Lang/AbstractType.php
  src/php/Lang/IteratorComparatorTrait.php
  src/php/Lang/PhelArray.php
  src/php/Lang/Set.php
  src/php/Lang/Table.php
  src/php/Lang/Tuple.php
  tests/phel/test/core.phel
  tests/phel/test/http.phel
  tests/php/Unit/Lang/PhelArrayTest.php
Labels: enhancement

#217 Use ExceptionPrinter in FormatCommand
  src/php/Command/CommandFacade.php
  src/php/Command/CommandFacadeInterface.php
  src/php/Command/CommandFactory.php
  src/php/Command/FormatCommand.php
  src/php/Command/Shared/CommandIoInterface.php
  src/php/Command/Shared/CommandSystemIo.php
  src/php/Compiler/Parser/Parser.php
  src/php/Compiler/Parser/ParserInterface.php
  src/php/Formatter/Formatter.php
  src/php/Formatter/FormatterInterface.php
  tests/php/Integration/Command/FormatCommandTest.php
Labels: enhancement

#219 Restructure phel core tests
  tests/phel/test/core.phel
  tests/phel/test/core/basic-constructors.phel
  tests/phel/test/core/basic-sequence-operation.phel
  tests/phel/test/core/bitwise-operation.phel
  tests/phel/test/core/boolean-operation.phel
  tests/phel/test/core/control-structures.phel
  tests/phel/test/core/for-loop.phel
  tests/phel/test/core/function-operation.phel
  tests/phel/test/core/math-operation.phel
  tests/phel/test/core/more-sequence-operation.phel
  tests/phel/test/core/print-operation.phel
  tests/phel/test/core/sequence-functions.phel
  tests/phel/test/core/sequence-operation.phel
  tests/phel/test/core/set-operation.phel
  tests/phel/test/core/threading-macros.phel
  tests/phel/test/core/type-operation.phel
  tests/phel/test/http.phel
Labels: refactoring

#220 Improve exceptions triggered from EvalEmitter
  src/php/Compiler/Analyzer/Analyzer.php
  src/php/Compiler/Analyzer/AnalyzerInterface.php
  src/php/Compiler/Emitter/Emitter.php
  src/php/Compiler/Emitter/EmitterInterface.php
  src/php/Compiler/Emitter/EvalEmitter.php
  src/php/Compiler/Emitter/EvalEmitterInterface.php
  src/php/Compiler/EvalCompiler.php
  src/php/Compiler/FileCompiler.php
  src/php/Compiler/FileCompilerInterface.php
  src/php/Compiler/Reader/ReaderInterface.php
  src/php/Exceptions/CompiledCodeIsMalformedException.php
  src/php/Exceptions/FileException.php
  src/php/Runtime/Runtime.php
Labels: enhancement

#218 Documentation v0.1.0
  Changelog.md
  doc/content/_index.md
  doc/content/documentation/getting-started.md
  doc/content/documentation/repl.md
  doc/sass/_base.scss
Labels: documentation
