Repository phel-lang/phel-lang, pull requests merged in 2021-02, with the labels that each got.

#222 Update infection
  .gitignore
  build/Dockerfile
  composer.json
  composer.lock
  infection.json.dist
  phpunit.xml.dist
  tests/php/Integration/Command/FormatCommandTest.php
Labels: refactoring

#225 Update composer in Dockerfile
  build/Dockerfile
  composer.lock
Labels: dependencies

#227 Add rule void_return to php_cs
  .php_cs.dist
  src/php/Compiler/Lexer/TokenStream.php
  tests/php/Unit/Compiler/Analyzer/TupleSymbol/DefSymbolTest.php
  tests/php/Unit/Compiler/Analyzer/TupleSymbol/InvokeSymbolTest.php
  tests/php/Unit/Compiler/Analyzer/TupleSymbol/LoopSymbolTest.php
  tests/php/Unit/Compiler/Reader/ReaderTest.php
  tests/php/Unit/Lang/SetTest.php
  tests/php/Unit/Lang/SourceLocationTest.php
  tests/php/Unit/Lang/SymbolTest.php
  tests/php/Unit/Lang/TruthyTest.php
Labels: enhancement

#229 Refactor some NodeEmitters
  src/php/Compiler/Emitter/OutputEmitter/NodeEmitter/CallEmitter.php
  src/php/Compiler/Emitter/OutputEmitter/NodeEmitter/DefStructEmitter.php
  src/php/Compiler/Emitter/OutputEmitter/NodeEmitter/IfEmitter.php
  src/php/Compiler/Emitter/OutputEmitter/NodeEmitter/NsEmitter.php
Labels: refactoring

#230 Reorganize commands
  src/php/Command/CommandFacade.php
  src/php/Command/CommandFactory.php
  src/php/Command/CommandFactoryInterface.php
  src/php/Command/Exceptions/ExitException.php
  src/php/Command/Format/FormatCommand.php
  src/php/Command/Repl/Exceptions/ExitException.php
  src/php/Command/Repl/ReplCommand.php
  src/php/Command/Run/Exceptions/CannotLoadNamespaceException.php
  src/php/Command/Run/RunCommand.php
  src/php/Command/Shared/Exceptions/ExtractorException.php
  src/php/Command/Shared/NamespaceExtractor.php
  src/php/Command/Test/Exceptions/CannotFindAnyTestsException.php
  src/php/Command/Test/TestCommand.php
  src/php/PhelFacade.php
  src/php/Runtime/RuntimeInterface.php
  tests/php/Integration/Command/Format/Fixtures/bad-format.phel
  tests/php/Integration/Command/Format/Fixtures/good-format.phel
  tests/php/Integration/Command/Format/FormatCommandTest.php
  tests/php/Integration/Command/Repl/Fixtures/exit-multiline-mode-with-ctrl-d.test
  tests/php/Integration/Command/Repl/Fixtures/simple-add-multiline.test
  tests/php/Integration/Command/Repl/Fixtures/simple-add.test
  tests/php/Integration/Command/Repl/Fixtures/undefined-symbol.test
  tests/php/Integration/Command/Repl/Fixtures/unexpected-token.test
  tests/php/Integration/Command/Repl/Fixtures/unterminated-list-multiline-with-empty-lines.test
  tests/php/Integration/Command/Repl/Fixtures/unterminated-list-multiline.test
  tests/php/Integration/Command/Repl/InputLine.php
  tests/php/Integration/Command/Repl/ReplCommandTest.php
  tests/php/Integration/Command/Repl/ReplTestIo.php
  tests/php/Integration/Command/Run/Fixtures/test-script-not-parsable.phel
  tests/php/Integration/Command/Run/Fixtures/test-script-without-ns.phel
  tests/php/Integration/Command/Run/Fixtures/test-script.phel
  tests/php/Integration/Command/Run/RunCommandTest.php
  tests/php/Integration/Command/Test/Fixtures/test-cmd-project-failure/composer.json
  tests/php/Integration/Command/Test/Fixtures/test-cmd-project-failure/tests/test1.phel
  tests/php/Integration/Command/Test/Fixtures/test-cmd-project-success/composer.json
  tests/php/Integration/Command/Test/Fixtures/test-cmd-project-success/tests/test1.phel
  tests/php/Integration/Command/Test/Fixtures/test-cmd-project-success/tests/test2.phel
  tests/php/Integration/Command/Test/TestCommandTest.php
Labels: refactoring

#226 Create ExportCommand
  .gitignore
  composer.json
  doc/content/documentation/configuration.md
  doc/content/documentation/php-interop.md
  phel
  src/php/AbstractPhelConfig.php
  src/php/Command/CommandConfig.php
  src/php/Command/CommandConfigInterface.php
  src/php/Command/CommandFacade.php
  src/php/Command/CommandFacadeInterface.php
  src/php/Command/CommandFactory.php
  src/php/Command/CommandFactoryInterface.php
  src/php/Command/Export/DirectoryRemover.php
  src/php/Command/Export/DirectoryRemoverInterface.php
  src/php/Command/Export/ExportCommand.php
  src/php/Command/Export/FunctionsToExportFinder.php
  src/php/Command/Export/FunctionsToExportFinderInterface.php
  src/php/Command/Shared/Exceptions/ExtractorException.php
  src/php/Command/Shared/NamespaceExtractor.php
  src/php/Command/Shared/NamespaceExtractorInterface.php
  src/php/Command/Test/TestCommand.php
  src/php/Interop/Generator/Builder/CompiledPhpClassBuilder.php
  src/php/Interop/Generator/Builder/CompiledPhpMethodBuilder.php
  src/php/Interop/Generator/Builder/WrapperRelativeFilenamePathBuilder.php
  src/php/Interop/Generator/WrapperGenerator.php
  src/php/Interop/Generator/WrapperGeneratorInterface.php
  src/php/Interop/InteropConfig.php
  src/php/Interop/InteropConfigInterface.php
  src/php/Interop/InteropFactory.php
  src/php/Interop/InteropFactoryInterface.php
  src/php/Interop/PhelCallerTrait.php
  src/php/Interop/ReadModel/FunctionToExport.php
  src/php/Interop/ReadModel/Wrapper.php
  src/php/PhelConfigInterface.php
  src/php/PhelFacade.php
  tests/php/Integration/Command/Export/ExportCommandTest.php
  tests/php/Integration/Command/Export/Fixtures/test-cmd-export-multiple/composer.json
  tests/php/Integration/Command/Export/Fixtures/test-cmd-export-multiple/src/adder.phel
  tests/php/Integration/Command/Export/Fixtures/test-cmd-export-multiple/src/multiplier.phel
  tests/php/Integration/Command/Format/FormatCommandTest.php
  tests/php/Integration/Command/Run/RunCommandTest.php
  tests/php/Integration/Command/Test/TestCommandTest.php
  tests/php/Integration/Interop/CallPhelTest.php
  tests/php/Integration/Interop/ExampleWrapper.php
  tests/php/Integration/Util/DirectoryUtil.php
  tests/php/Unit/Interop/Generator/Builder/WrapperRelativeFilenamePathBuilderTest.php
  tests/php/Unit/Interop/Generator/WrapperGeneratorTest.php
Labels: enhancement

#232 Minor exceptions clean-up
  src/php/Command/CommandFacade.php
  src/php/Command/CommandFacadeInterface.php
  src/php/Command/Export/ExportCommand.php
  src/php/Command/Export/FunctionsToExportFinderInterface.php
  src/php/Command/Format/FormatCommand.php
  src/php/Command/Shared/NamespaceExtractor.php
  src/php/Compiler/EvalCompiler.php
  src/php/Compiler/FileCompiler.php
  src/php/Compiler/Lexer/Exceptions/LexerValueException.php
  src/php/Compiler/Lexer/Lexer.php
  src/php/Compiler/Lexer/LexerInterface.php
  src/php/Formatter/AbstractZipper.php
  src/php/Formatter/Exceptions/ZipperException.php
  src/php/Formatter/Formatter.php
  src/php/Formatter/FormatterInterface.php
  src/php/Formatter/ParseTreeZipper.php
  src/php/Formatter/Rules/RemoveSurroundingWhitespaceRule.php
  src/php/Formatter/Rules/RuleInterface.php
  src/php/PhelFacade.php
  tests/php/Unit/Formatter/ZipperTest.php
Labels: refactoring

#233 Refactor Formatter
  src/php/Command/Format/FormatCommand.php
  src/php/Formatter/Formatter.php
  src/php/Formatter/FormatterInterface.php
Labels: refactoring

#236 Handle exceptions inside commands
  src/php/Command/CommandFacade.php
  src/php/Command/CommandFacadeInterface.php
  src/php/Command/CommandFactory.php
  src/php/Command/Export/ExportCommand.php
  src/php/Command/Format/FormatCommand.php
  src/php/Command/Repl/ReplCommand.php
  src/php/Command/Repl/ReplCommandIoInterface.php
  src/php/Command/Repl/ReplCommandSystemIo.php
  src/php/Command/Run/RunCommand.php
  src/php/Command/Shared/CommandIoInterface.php
  src/php/Command/Shared/CommandSystemIo.php
  src/php/Command/Test/Exceptions/CannotFindAnyTestsException.php
  src/php/Command/Test/TestCommand.php
  src/php/Compiler/Exceptions/CompilerException.php
  src/php/PhelFacade.php
  tests/php/Integration/Command/Repl/ReplCommandTest.php
  tests/php/Integration/Command/Repl/ReplTestIo.php
  tests/php/Integration/Command/Run/RunCommandTest.php
  tests/php/Integration/Command/Test/TestCommandTest.php
Labels: refactoring

#237 Add missig catch in run command
  src/php/Command/Run/RunCommand.php
  tests/php/Integration/Command/Test/TestCommandTest.php
Labels: refactoring

#238 Remove docker
  Readme.md
  build/Dockerfile
  docker-compose.yml
Labels: enhancement
