Repository phel-lang/phel-lang, pull requests merged in 2021-05, with the labels that each got.

#263 Improve benchmark test cases
  .github/workflows/ci.yml
  composer.json
  composer.lock
  phpbench.json
  tests/php/Benchmark/Lang/Collections/Map/PersistentHashMapAddBench.php
  tests/php/Benchmark/Lang/Collections/Map/PersistentHashMapBench.php
  tests/php/Benchmark/Lang/Collections/SimpleEqualizer.php
  tests/php/Benchmark/Lang/Collections/SimpleHasher.php
  tests/php/Benchmark/Lang/Collections/Vector/PersistentVectorBench.php
  tests/php/Benchmark/Lang/Collections/Vector/SimpleImmutableVector.php
  tests/php/Benchmark/Lang/Collections/Vector/SimpleImmutableVectorBench.php
  tests/php/Benchmark/Lang/Collections/Vector/TransientVectorBench.php
  tests/php/Benchmark/Lang/Collections/Vector/VectorA.php
  tests/php/Benchmark/Lang/Collections/Vector/VectorAddBench.php
  tests/php/Unit/Lang/Collections/SimpleEqualizer.php
  tests/php/Unit/Lang/Collections/Vector/SubVectorTest.php
Labels: enhancement

#266 Update API doc
  doc/content/documentation/api.md
  src/phel/core/type-operation.phel
Labels: documentation

#259 Adding re-seq phel function
  Changelog.md
  doc/content/documentation/api.md
  src/phel/core.phel
  src/phel/core/regex-functions.phel
  tests/phel/test/core/regex-functions.phel
Labels: enhancement

#270 Update documentation for data structures
  doc/content/_index.md
  doc/content/documentation/array-table-and-struct.md
  doc/content/documentation/basic-types.md
  doc/content/documentation/control-flow.md
  doc/content/documentation/data-structures.md
  doc/content/documentation/destructuring.md
  doc/content/documentation/functions-and-recursion.md
  doc/content/documentation/global-and-local-bindings.md
  doc/content/documentation/html-rendering.md
  doc/content/documentation/http-request-and-response.md
  doc/content/documentation/macros.md
  doc/content/documentation/php-interop.md
  doc/content/documentation/truth-and-boolean-operations.md
  doc/content/documentation/tuple.md
  doc/syntaxes/phel.sublime-syntax
  src/phel/core/sequence-operation.phel
Labels: documentation

#246 Fixes partition function.
  src/phel/core/sequence-functions.phel
  tests/phel/test/core/sequence-functions.phel
Labels: bug

#267 Add contains? phel function
  Changelog.md
  src/phel/core.phel
  src/phel/core/boolean-operation.phel
  src/phel/core/type-operation.phel
  src/php/Lang/Collections/HashSet/PersistentHashSet.php
  src/php/Lang/Collections/HashSet/PersistentHashSetInterface.php
  src/php/Lang/Collections/HashSet/TransientHashSet.php
  src/php/Lang/Collections/HashSet/TransientHashSetInterface.php
  src/php/Lang/Collections/LinkedList/EmptyList.php
  src/php/Lang/Collections/LinkedList/PersistentList.php
  src/php/Lang/Collections/LinkedList/PersistentListInterface.php
  src/php/Lang/Collections/Map/AbstractPersistentMap.php
  src/php/Lang/Collections/Map/PersistentArrayMap.php
  src/php/Lang/Collections/Map/PersistentHashMap.php
  src/php/Lang/Collections/Map/PersistentMapInterface.php
  src/php/Lang/Collections/Map/TransientArrayMap.php
  src/php/Lang/Collections/Map/TransientHashMap.php
  src/php/Lang/Collections/Map/TransientMapInterface.php
  src/php/Lang/Collections/Struct/AbstractPersistentStruct.php
  src/php/Lang/Collections/Vector/AbstractPersistentVector.php
  src/php/Lang/Collections/Vector/PersistentVectorInterface.php
  src/php/Lang/Collections/Vector/SubVector.php
  src/php/Lang/Collections/Vector/TransientVector.php
  src/php/Lang/Collections/Vector/TransientVectorInterface.php
  src/php/Lang/ContainsInterface.php
  tests/phel/test/core/boolean-operation.phel
  tests/phel/test/core/sequence-operation.phel
  tests/php/Unit/Lang/Collections/LinkedList/EmptyListTest.php
  tests/php/Unit/Lang/Collections/LinkedList/PersistentListTest.php
  tests/php/Unit/Lang/Collections/Map/PersistentArrayMapTest.php
  tests/php/Unit/Lang/Collections/Map/PersistentHashMapTest.php
  tests/php/Unit/Lang/Collections/Map/TransientArrayMapTest.php
  tests/php/Unit/Lang/Collections/Map/TransientHashMapTest.php
  tests/php/Unit/Lang/Collections/Vector/PersistentVectorTest.php
Labels: enhancement

#274 Split Emitter and Evaluator
  src/php/Command/Run/RunCommand.php
  src/php/Command/Test/TestCommand.php
  src/php/Compiler/Compiler/EvalCompiler.php
  src/php/Compiler/Compiler/FileCompiler.php
  src/php/Compiler/Compiler/FileCompilerInterface.php
  src/php/Compiler/CompilerFacade.php
  src/php/Compiler/CompilerFacadeInterface.php
  src/php/Compiler/CompilerFactory.php
  src/php/Compiler/Emitter/Emitter.php
  src/php/Compiler/Emitter/EmitterInterface.php
  src/php/Compiler/Evaluator/EvaluatorInterface.php
  src/php/Compiler/Evaluator/Exceptions/CompiledCodeIsMalformedException.php
  src/php/Compiler/Evaluator/Exceptions/FileException.php
  src/php/Compiler/Evaluator/RequireEvaluator.php
  src/php/Interop/ExportFinder/FunctionsToExportFinder.php
  src/php/Interop/ExportFinder/FunctionsToExportFinderInterface.php
  src/php/Runtime/Runtime.php
  src/php/Runtime/RuntimeInterface.php
  tests/php/Integration/Compiler/Reader/ReaderTest.php
  tests/php/Integration/IntegrationTest.php
Labels: refactoring

#278 Using symfony/console
  composer.json
  composer.lock
  phel
  src/php/Command/CommandFacade.php
  src/php/Command/CommandFacadeInterface.php
  src/php/Command/Export/ExportCommand.php
  src/php/Command/Format/FormatCommand.php
  src/php/Command/Repl/ReplCommand.php
  src/php/Command/Run/RunCommand.php
  src/php/Command/Test/TestCommand.php
  src/php/PhelDependencyProvider.php
  src/php/PhelFacade.php
  src/php/PhelFactory.php
  tests/php/Integration/Command/Export/ExportCommandTest.php
  tests/php/Integration/Command/Format/FormatCommandTest.php
  tests/php/Integration/Command/Repl/ReplCommandTest.php
  tests/php/Integration/Command/Run/RunCommandTest.php
  tests/php/Integration/Command/Test/TestCommandTest.php
Labels: refactoring

#279 Some clean up for the current commands
  src/php/Command/CommandFactory.php
  src/php/Command/Export/Exceptions/NoFunctionsFoundException.php
  src/php/Command/Export/ExportCommand.php
  src/php/Command/Format/FormatCommand.php
  src/php/Command/Run/RunCommand.php
  src/php/Command/Shared/CommandExceptionWriter.php
  src/php/Command/Shared/CommandExceptionWriterInterface.php
  src/php/Command/Shared/CommandIoInterface.php
  src/php/Command/Shared/CommandSystemIo.php
  src/php/Command/Test/TestCommand.php
  src/php/Interop/ExportFinder/FunctionsToExportFinder.php
  src/php/Interop/ExportFinder/FunctionsToExportFinderInterface.php
  src/php/Interop/InteropFacade.php
  src/php/Interop/InteropFacadeInterface.php
  src/php/Runtime/Exceptions/PhelRuntimeException.php
  src/php/Runtime/Extractor/ExtractorException.php
  src/php/Runtime/Extractor/NamespaceExtractor.php
  src/php/Runtime/RuntimeFactory.php
  tests/php/Integration/Command/AbstractCommandTest.php
  tests/php/Integration/Command/Export/ExportCommandTest.php
  tests/php/Integration/Command/Format/FormatCommandTest.php
  tests/php/Integration/Command/Repl/ReplCommandTest.php
  tests/php/Integration/Command/Run/RunCommandTest.php
  tests/php/Integration/Command/Test/TestCommandTest.php
Labels: refactoring

#243 Adding compiler_module ADR
  adrs/php/0002_compiler_module.md
Labels: documentation

#283 Replace can not by cannot
  src/phel/core/sequence-functions.phel
  src/phel/core/sequence-operation.phel
  src/phel/http.phel
  src/phel/repl.phel
  src/php/Compiler/Analyzer/TypeAnalyzer/AnalyzeSymbol.php
  src/php/Compiler/Analyzer/TypeAnalyzer/SpecialForm/Binding/BindingValidator.php
  src/php/Compiler/Analyzer/TypeAnalyzer/SpecialForm/NsSymbol.php
  src/php/Compiler/Evaluator/Exceptions/FileException.php
  src/php/Compiler/Parser/ParserNode/ListNode.php
  src/php/Compiler/Parser/ParserNode/QuoteNode.php
  src/php/Compiler/Reader/Reader.php
  src/php/Formatter/Exceptions/ZipperException.php
  src/php/Formatter/Formatter/AbstractZipper.php
  src/php/Lang/Collections/LinkedList/EmptyList.php
  src/php/Lang/Collections/Vector/SubVector.php
  src/php/Printer/Printer.php
  src/php/Printer/TypePrinter/NonPrintableClassPrinter.php
  src/php/Runtime/Runtime.php
  tests/phel/test/http.phel
  tests/php/Integration/Command/Repl/Fixtures/undefined-symbol.test
  tests/php/Unit/Compiler/Analyzer/AnalyzeSymbolTest.php
  tests/php/Unit/Compiler/Analyzer/SpecialForm/Binding/BindingValidatorTest.php
  tests/php/Unit/Compiler/Analyzer/SpecialForm/InvokeSymbolTest.php
  tests/php/Unit/Printer/TypePrinter/NonPrintableClassPrinterTest.php
Labels: documentation

#282 Refactored Emitter and OutputEmitter
  src/php/Compiler/CompilerFactory.php
  src/php/Compiler/Emitter/Emitter.php
  src/php/Compiler/Emitter/OutputEmitter.php
  src/php/Compiler/Emitter/OutputEmitter/SourceMap/SourceMapState.php
  src/php/Compiler/Emitter/OutputEmitterInterface.php
Labels: refactoring

#284 Add execution time and resource usage
  composer.json
  composer.lock
  src/php/Command/Run/RunCommand.php
  src/php/Command/Test/TestCommand.php
  tests/php/Integration/Command/Test/TestCommandTest.php
Labels: enhancement

#285 Add a filter option to test command
  src/phel/test.phel
  src/php/Command/Test/TestCommand.php
  src/php/Command/Test/TestCommandOptions.php
  tests/php/Unit/Command/Test/TestCommandOptionsTest.php
Labels: enhancement

#291 Refactoring test.phel
  src/phel/test.phel
Labels: refactoring

#292 Use the CompilerFacade form the IntegrationTests
  src/php/Compiler/Compiler/CodeCompiler.php
  src/php/Compiler/Compiler/CodeCompilerInterface.php
  src/php/Compiler/CompilerFacade.php
  src/php/Compiler/CompilerFacadeInterface.php
  src/php/Compiler/CompilerFactory.php
  src/php/Formatter/Formatter/Formatter.php
  src/php/Runtime/Runtime.php
  tests/php/Integration/Compiler/Reader/ReaderTest.php
  tests/php/Integration/IntegrationTest.php
Labels: refactoring

#293 Merged core lib into one file and removed the load function
  Changelog.md
  src/phel/core.phel
  src/phel/core/basic-constructors.phel
  src/phel/core/basic-sequence-operation.phel
  src/phel/core/bitwise-operation.phel
  src/phel/core/boolean-operation.phel
  src/phel/core/control-structures.phel
  src/phel/core/for-loop.phel
  src/phel/core/function-operation.phel
  src/phel/core/math-operation.phel
  src/phel/core/more-sequence-operation.phel
  src/phel/core/print-operation.phel
  src/phel/core/regex-functions.phel
  src/phel/core/sequence-functions.phel
  src/phel/core/sequence-operation.phel
  src/phel/core/set-operation.phel
  src/phel/core/threading-macros.phel
  src/phel/core/type-operation.phel
Labels: refactoring

#295 Move NamespaceExtractor from Compile module to its own module
  src/php/Command/CommandDependencyProvider.php
  src/php/Command/CommandFactory.php
  src/php/Command/Run/RunCommand.php
  src/php/Command/Test/TestCommand.php
  src/php/Compiler/Compiler/NamespaceExtractor.php
  src/php/Compiler/CompilerFacade.php
  src/php/Compiler/CompilerFacadeInterface.php
  src/php/Compiler/CompilerFactory.php
  src/php/Interop/ExportFinder/FunctionsToExportFinder.php
  src/php/Interop/InteropDependencyProvider.php
  src/php/Interop/InteropFactory.php
  src/php/NamespaceExtractor/NamespaceExtractorDependencyProvider.php
  src/php/NamespaceExtractor/NamespaceExtractorFacade.php
  src/php/NamespaceExtractor/NamespaceExtractorFacadeInterface.php
  src/php/NamespaceExtractor/NamespaceExtractorFactory.php
Labels: refactoring

#294 Moved namespace extractor code to the compiler module
  src/php/Command/CommandConfig.php
  src/php/Command/CommandDependencyProvider.php
  src/php/Command/CommandFactory.php
  src/php/Command/Run/RunCommand.php
  src/php/Command/Test/TestCommand.php
  src/php/Compiler/Compiler/ExtractorException.php
  src/php/Compiler/Compiler/NamespaceExtractor.php
  src/php/Compiler/Compiler/NamespaceExtractorInterface.php
  src/php/Compiler/CompilerFacade.php
  src/php/Compiler/CompilerFacadeInterface.php
  src/php/Interop/ExportFinder/FunctionsToExportFinder.php
  src/php/Interop/ExportFinder/FunctionsToExportFinderInterface.php
  src/php/Interop/InteropConfig.php
  src/php/Interop/InteropDependencyProvider.php
  src/php/Interop/InteropFactory.php
  src/php/NamespaceExtractor/NamespaceExtractorDependencyProvider.php
  src/php/NamespaceExtractor/NamespaceExtractorFacade.php
  src/php/NamespaceExtractor/NamespaceExtractorFacadeInterface.php
  src/php/NamespaceExtractor/NamespaceExtractorFactory.php
  src/php/Runtime/RuntimeFacade.php
  src/php/Runtime/RuntimeFacadeInterface.php
  src/php/Runtime/RuntimeFactory.php
Labels: refactoring
