Repository phel-lang/phel-lang, pull requests merged in 2021-06, with the labels that each got.

#300 Minor clean-up on Code|EvalCompiler
  src/php/Compiler/Compiler/CodeCompiler.php
  src/php/Compiler/Compiler/EvalCompiler.php
  src/php/Compiler/Compiler/EvalCompilerInterface.php
Labels: refactoring

#301 Minor refactor on CommandFactory
  src/php/Command/CommandConfig.php
  src/php/Command/CommandFactory.php
Labels: refactoring

#304 Make NamespaceExtractor more independent
  src/php/Command/Test/TestCommand.php
  src/php/Interop/ExportFinder/FunctionsToExportFinder.php
  src/php/Interop/ExportFinder/FunctionsToExportFinderInterface.php
  src/php/NamespaceExtractor/Extractor/ExtractorException.php
  src/php/NamespaceExtractor/Extractor/NamespaceExtractor.php
  src/php/NamespaceExtractor/Extractor/NamespaceExtractorInterface.php
  src/php/NamespaceExtractor/Extractor/NamespaceInformation.php
  src/php/NamespaceExtractor/NamespaceExtractorFacade.php
  src/php/NamespaceExtractor/NamespaceExtractorFacadeInterface.php
  src/php/NamespaceExtractor/NamespaceExtractorFactory.php
Labels: refactoring

#308 Update PHP CS Fixer
  .github/workflows/ci.yml
  .gitignore
  .php-cs-fixer.dist.php
  composer.json
  composer.lock
  src/php/Compiler/Emitter/OutputEmitter/NodeEmitter/NsEmitter.php
  src/php/Compiler/Lexer/TokenStream.php
  src/php/Formatter/Formatter/ParseTreeZipper.php
  src/php/Lang/Collections/LinkedList/PersistentListInterface.php
  src/php/Lang/Collections/Map/PersistentMapInterface.php
  src/php/Lang/Collections/Map/TransientMapInterface.php
  src/php/Lang/Collections/Map/TransientMapWrapper.php
Labels: enhancement

#306 Remove passing by ref the array to the push function
  Changelog.md
  src/phel/core.phel
  tests/phel/test/core/sequence-operation.phel
Labels: bug
