Repository phel-lang/phel-lang, pull requests merged in 2021-03, with the labels that each got.

#242 Create PhelFacadeFactory
  phel
  src/php/PhelConfigInterface.php
  src/php/PhelFacadeFactory.php
Labels: refactoring

#245 Adding take-last
  src/phel/core/sequence-functions.phel
  tests/phel/test/core/sequence-functions.phel
Labels: enhancement

#248 Rename fmt to format
  src/php/Command/Format/FormatCommand.php
  src/php/PhelFacade.php
Labels: documentation
