Repository phel-lang/phel-lang, pull requests merged in 2021-12, with the labels that each got.

#385 Define interface and let struct implement them
  src/phel/core.phel
  src/php/Compiler/Analyzer/Analyzer.php
  src/php/Compiler/Analyzer/AnalyzerInterface.php
  src/php/Compiler/Analyzer/Ast/DefInterfaceMethod.php
  src/php/Compiler/Analyzer/Ast/DefInterfaceNode.php
  src/php/Compiler/Analyzer/Ast/DefStructInterface.php
  src/php/Compiler/Analyzer/Ast/DefStructMethod.php
  src/php/Compiler/Analyzer/Ast/DefStructNode.php
  src/php/Compiler/Analyzer/Ast/PhpClassNameNode.php
  src/php/Compiler/Analyzer/Environment/GlobalEnvironment.php
  src/php/Compiler/Analyzer/Environment/GlobalEnvironmentInterface.php
  src/php/Compiler/Analyzer/TypeAnalyzer/AnalyzePersistentList.php
  src/php/Compiler/Analyzer/TypeAnalyzer/SpecialForm/DefInterfaceSymbol.php
  src/php/Compiler/Analyzer/TypeAnalyzer/SpecialForm/DefStructSymbol.php
  src/php/Compiler/Emitter/OutputEmitter/NodeEmitter/DefInterfaceEmitter.php
  src/php/Compiler/Emitter/OutputEmitter/NodeEmitter/DefStructEmitter.php
  src/php/Compiler/Emitter/OutputEmitter/NodeEmitter/FnAsClassEmitter.php
  src/php/Compiler/Emitter/OutputEmitter/NodeEmitter/MethodEmitter.php
  src/php/Compiler/Emitter/OutputEmitter/NodeEmitterFactory.php
  src/php/Lang/Symbol.php
  tests/php/Integration/Fixtures/Def/definterface-with-methods.test
  tests/php/Integration/Fixtures/Def/definterface.test
  tests/php/Integration/Fixtures/Def/defstruct-interface-without-methods.test
  tests/php/Integration/Fixtures/Def/defstruct-one-interface.test
  tests/php/Integration/Fixtures/Def/defstruct-two-interfaces.test
  tests/php/Integration/Fixtures/Fn/fn-this-parameter.test
  tests/php/Unit/Compiler/Analyzer/Environment/GlobalEnvironmentTest.php
  tests/php/Unit/Compiler/Analyzer/SpecialForm/DefStructSymbolTest.php
  tests/php/Unit/Compiler/Emitter/OutputEmitter/NodeEmitter/FnAsClassEmitterTest.php
Labels: enhancement

#393 Add contributing page
  .github/CONTRIBUTING.md
  .github/ISSUE_TEMPLATE/BUG.md
  .github/ISSUE_TEMPLATE/FEATURE_REQUEST.md
  .github/PULL_REQUEST_TEMPLATE.md
  .php-cs-fixer.dist.php
  composer.json
Labels: documentation

#392 Add contributor-covenant code of conduct
  .github/CODE_OF_CONDUCT.md
Labels: documentation

#394 Refactor GlobalEnvironment
  src/php/Compiler/Analyzer/Environment/GlobalEnvironment.php
Labels: refactoring

#395 Refactoring some output emitters
  src/php/Compiler/Analyzer/TypeAnalyzer/SpecialForm/DefInterfaceSymbol.php
  src/php/Compiler/Emitter/OutputEmitter/NodeEmitter/DefInterfaceEmitter.php
  src/php/Compiler/Emitter/OutputEmitter/NodeEmitter/DefStructEmitter.php
  src/php/Compiler/Emitter/OutputEmitter/NodeEmitter/FnAsClassEmitter.php
  src/php/Compiler/Emitter/OutputEmitter/NodeEmitter/MethodEmitter.php
  src/php/Compiler/Emitter/OutputEmitter/NodeEmitter/PhpNewEmitter.php
  src/php/Compiler/Emitter/OutputEmitter/NodeEmitter/PhpObjectCallEmitter.php
  src/php/Compiler/Emitter/OutputEmitter/NodeEmitter/RecurEmitter.php
  src/php/Compiler/Emitter/OutputEmitter/NodeEmitter/TryEmitter.php
Labels: refactoring

#396 Move contributing section from Readme.md to CONTRIBUTING.md
  .github/CONTRIBUTING.md
  Readme.md
Labels: documentation

#399 Update README
  README.md
Labels: documentation

#401 Sorting alphanum the .gitignore content
  .gitignore
Labels: refactoring

#402 Expose ExceptionPrinter from CommandFacade
  src/phel/test.phel
  src/php/Command/CommandFacade.php
Labels: bug

#400 Separate the CI tests on diff jobs
  .github/workflows/ci.yml
Labels: enhancement

#403 Upgrade PHP to require >=8.0
  .github/workflows/ci.yml
  composer.json
  composer.lock
Labels: enhancement

#404 Add CallablePrinter
  src/php/Printer/Printer.php
  src/php/Printer/TypePrinter/FnPrinter.php
  tests/php/Unit/Printer/TypePrinter/FnPrinterTest.php
Labels: enhancement

#406 PHP 8.1 support
  .github/workflows/ci.yml
  src/phel/http.phel
  src/php/Compiler/Lexer/TokenStream.php
  src/php/Lang/Collections/HashSet/TransientHashSet.php
  src/php/Lang/Collections/LinkedList/EmptyList.php
  src/php/Lang/Collections/LinkedList/PersistentList.php
  src/php/Lang/Collections/Map/AbstractPersistentMap.php
  src/php/Lang/Collections/Map/ArrayNode.php
  src/php/Lang/Collections/Map/ArrayNodeIterator.php
  src/php/Lang/Collections/Map/HashCollisionNodeIterator.php
  src/php/Lang/Collections/Map/IndexedNode.php
  src/php/Lang/Collections/Map/IndexedNodeIterator.php
  src/php/Lang/Collections/Map/TransientArrayMap.php
  src/php/Lang/Collections/Map/TransientHashMap.php
  src/php/Lang/Collections/Map/TransientMapWrapper.php
  src/php/Lang/Collections/Struct/AbstractPersistentStruct.php
  src/php/Lang/Collections/Vector/AbstractPersistentVector.php
  src/php/Lang/Collections/Vector/RangeIterator.php
  src/php/Lang/Collections/Vector/TransientVector.php
  src/php/Lang/PhelArray.php
  src/php/Lang/Set.php
  src/php/Lang/Table.php
Labels: enhancement

#405 Added a :reduce option for the for-loop
  src/phel/core.phel
  tests/phel/test/core/for-loop.phel
Labels: enhancement

#414 Update dependencies
  composer.json
  composer.lock
Labels: dependencies

#412 Keep Munge creation inside its module
  src/php/Build/BuildFactory.php
  src/php/Build/Compile/ProjectCompiler.php
  src/php/Compiler/CompilerFacade.php
  src/php/Compiler/CompilerFacadeInterface.php
  src/php/Compiler/CompilerFactory.php
Labels: refactoring

#413 Remove unused HtmlExceptionPrinter
  src/php/Command/Shared/Exceptions/HtmlExceptionPrinter.php
Labels: refactoring

#415 Adding ADRs for different modules
  adrs/php/0002_compiler_module.md
  adrs/php/0003_build_module.md
  adrs/php/0004_command_module.md
  adrs/php/0005_formatter_module.md
  adrs/php/0006_interop_module.md
  adrs/php/0007_run_module.md
  phel-config.php
Labels: documentation

#416 Fix formatter facade tests
  tests/php/Integration/Formatter/FormatterFacadeTest.php
Labels: refactoring, pure testing

#417 Move format() inside FormatCommand
  src/php/Formatter/Command/FormatCommand.php
  src/php/Formatter/FormatterFacade.php
  src/php/Formatter/FormatterFactory.php
  tests/php/Integration/Formatter/FormatterFacadeTest.php
Labels: refactoring
