Repository phel-lang/phel-lang, pull requests merged in 2021-08, with the labels that each got.

#324 Update dependencies
  composer.lock
Labels: dependencies

#325 Update Gacela
  composer.json
  composer.lock
  src/php/AbstractPhelConfig.php
  src/php/Command/CommandConfig.php
  src/php/Interop/InteropConfig.php
  src/php/Runtime/RuntimeConfig.php
  tests/php/Integration/Command/Export/ExportCommandTest.php
  tests/php/Integration/Command/Format/FormatCommandTest.php
  tests/php/Integration/Command/Run/RunCommandTest.php
  tests/php/Integration/Command/Test/TestCommandTest.php
  tests/php/Integration/Printer/PrinterTest.php
Labels: dependencies

#326 Create CommandFacade and use it as entry point instead of CommandFactory
  phel
  src/php/Command/CommandFacade.php
  tests/php/Integration/Command/AbstractCommandTest.php
  tests/php/Integration/Command/Export/ExportCommandTest.php
  tests/php/Integration/Command/Format/FormatCommandTest.php
  tests/php/Integration/Command/Run/RunCommandTest.php
  tests/php/Integration/Command/Test/TestCommandTest.php
Labels: refactoring

#318 Add spaceship operator function
  src/phel/core.phel
  tests/phel/test/core/sequence-functions.phel
Labels: enhancement

#329 Update Gacela 0.8
  composer.json
  composer.lock
  phel
  src/php/Command/CommandConfig.php
Labels: dependencies

#330 Add config platform php 7.4 to composer json
  composer.json
  composer.lock
Labels: dependencies

#331 Allow optional argv in RunCommand
  src/php/Command/Run/RunCommand.php
Labels: bug

#333 Renamed NamespaceExtractorFacade to BuildFacade
  src/php/Build/BuildDependencyProvider.php
  src/php/Build/BuildFacade.php
  src/php/Build/BuildFacadeInterface.php
  src/php/Build/BuildFactory.php
  src/php/Build/Extractor/ExtractorException.php
  src/php/Build/Extractor/NamespaceExtractor.php
  src/php/Build/Extractor/NamespaceExtractorInterface.php
  src/php/Build/Extractor/NamespaceInformation.php
  src/php/Command/CommandDependencyProvider.php
  src/php/Command/CommandFactory.php
  src/php/Command/Run/RunCommand.php
  src/php/Command/Test/TestCommand.php
  src/php/Interop/ExportFinder/FunctionsToExportFinder.php
  src/php/Interop/ExportFinder/FunctionsToExportFinderInterface.php
  src/php/Interop/InteropDependencyProvider.php
  src/php/Interop/InteropFactory.php
Labels: refactoring

#334 Extracted namespaces are now sorted based on their dependecies
  src/php/Build/BuildFacadeInterface.php
  src/php/Build/BuildFactory.php
  src/php/Build/Extractor/NamespaceExtractor.php
  src/php/Build/Extractor/NamespaceSorterInterface.php
  src/php/Build/Extractor/TopologicalNamespaceSorter.php
  tests/php/Integration/Command/Test/Fixtures/test-cmd-project-success/test2.phel
  tests/php/Unit/Build/Extractor/TopologicalSortingTest.php
Labels: refactoring
