Repository phel-lang/phel-lang, pull requests merged in 2022-04, with the labels that each got.

#459 Added read-string, eval and compile function to core library
  CHANGELOG.md
  src/phel/core.phel
  src/php/Compiler/Compiler/CodeCompiler.php
  src/php/Compiler/Compiler/CodeCompilerInterface.php
  src/php/Compiler/Compiler/EvalCompiler.php
  src/php/Compiler/Compiler/EvalCompilerInterface.php
  src/php/Compiler/CompilerFacade.php
  src/php/Compiler/CompilerFacadeInterface.php
  tests/phel/test/core.phel
Labels: enhancement

#460 Create a ConsoleBootstrap
  phel
  src/php/Console/ConsoleDependencyProvider.php
  src/php/Console/ConsoleFactory.php
  src/php/Console/Infrastructure/ConsoleBootstrap.php
Labels: refactoring

#462 Install PHPStan
  .github/workflows/ci.yml
  composer.json
  composer.lock
  phpstan.neon
  src/php/Lang/Collections/LinkedList/PersistentList.php
Labels: enhancement

#463 Improve phpmetrics usage
  composer.json
  phpmetrics-config.json
Labels: enhancement

#461 Remove constructor from CompileCommand
  composer.json
  composer.lock
  src/php/Build/BuildFacade.php
  src/php/Build/BuildFacadeInterface.php
  src/php/Build/BuildFactory.php
  src/php/Build/Command/CompileCommand.php
  src/php/Build/Compile/ProjectCompiler.php
  src/php/Console/ConsoleDependencyProvider.php
  tests/php/Integration/Build/Command/CompileCommandTest.php
Labels: enhancement

#466 Refactor FormatCommand to use the Facade
  src/php/Console/ConsoleDependencyProvider.php
  src/php/Formatter/Command/FormatCommand.php
  src/php/Formatter/Domain/Exception/FilePathException.php
  src/php/Formatter/Domain/PathsFormatter.php
  src/php/Formatter/FormatterFacade.php
  src/php/Formatter/FormatterFacadeInterface.php
  src/php/Formatter/FormatterFactory.php
  src/php/Formatter/Infrastructure/Command/FormatCommand.php
  src/php/Formatter/Infrastructure/IO/FileIoInterface.php
  src/php/Formatter/Infrastructure/IO/SystemFileIo.php
  tests/php/Integration/Formatter/Command/Format/FormatCommandTest.php
  tests/php/Integration/Formatter/FormatterFacadeTest.php
Labels: refactoring

#465 Remove constructor for TestCommand using RunFacade instead
  src/php/Console/ConsoleDependencyProvider.php
  src/php/Run/Command/TestCommand.php
  src/php/Run/RunFacade.php
  src/php/Run/RunFacadeInterface.php
  src/php/Run/RunFactory.php
  src/php/Run/Runner/NamespaceCollector.php
  tests/php/Benchmark/Command/CommandBench.php
  tests/php/Integration/Run/Command/Test/TestCommandProjectFailure/TestCommandProjectFailureTest.php
  tests/php/Integration/Run/Command/Test/TestCommandProjectSuccess/TestCommandProjectSuccessTest.php
Labels: refactoring

#468 Fix ReplCommandSystemIo when internal library_version is null
  CHANGELOG.md
  src/php/Run/Domain/Repl/ReplCommandSystemIo.php
Labels: bug

#469 Update gacela 0.17
  composer.json
  composer.lock
  src/php/Build/Command/CompileCommand.php
  src/php/Formatter/Infrastructure/Command/FormatCommand.php
  src/php/Run/Command/TestCommand.php
Labels: enhancement
