Repository phel-lang/phel-lang, pull requests merged in 2022-01, with the labels that each got.

#422 Fixes #408: Remove calls to GlobalEnvironmentSingleton in compiled code
  src/php/Compiler/Emitter/OutputEmitter/NodeEmitter/NsEmitter.php
  tests/php/Integration/Fixtures/Def/definterface-instance-of.test
  tests/php/Integration/Fixtures/Def/definterface-with-methods.test
  tests/php/Integration/Fixtures/Def/definterface.test
  tests/php/Integration/Fixtures/Def/namespace-def.test
  tests/php/Integration/Fixtures/Keyword/keywords.test
  tests/php/Integration/Fixtures/Let/loop-destructure.test
  tests/php/Integration/Fixtures/New/new-from-alias.test
  tests/php/Integration/Fixtures/Ns/munge-ns.test
  tests/php/Integration/Fixtures/Ns/require-file.test
  tests/php/Integration/Fixtures/Ns/require.test
  tests/php/Integration/Fixtures/Ns/use.test
  tests/php/Integration/Fixtures/Try/catch-from-ns-use.test
Labels: bug

#424 Adds a new function: coerce-in
  src/phel/core.phel
  tests/phel/test/core/math-operation.phel
Labels: enhancement

#425 Override method getDefintionMetadata by getDefinitionMetadata
  src/phel/repl.phel
  src/phel/test.phel
  src/php/Interop/ExportFinder/FunctionsToExportFinder.php
  src/php/Lang/Registry.php
Labels: refactoring

#427 Added support for inline optimization.
  src/phel/core.phel
  src/phel/repl.phel
  src/php/Compiler/Analyzer/TypeAnalyzer/SpecialForm/InvokeSymbol.php
  tests/php/Integration/Fixtures/Def/defstruct-one-interface.test
  tests/php/Integration/Fixtures/Def/defstruct-two-interfaces.test
  tests/php/Integration/Fixtures/Inline/bigger-equal.test
  tests/php/Integration/Fixtures/Inline/bigger.test
  tests/php/Integration/Fixtures/Inline/bit-and.test
  tests/php/Integration/Fixtures/Inline/bit-not.test
  tests/php/Integration/Fixtures/Inline/bit-or.test
  tests/php/Integration/Fixtures/Inline/bit-shift-left.test
  tests/php/Integration/Fixtures/Inline/bit-shift-right.test
  tests/php/Integration/Fixtures/Inline/bit-xor.test
  tests/php/Integration/Fixtures/Inline/dec.test
  tests/php/Integration/Fixtures/Inline/div.test
  tests/php/Integration/Fixtures/Inline/inc.test
  tests/php/Integration/Fixtures/Inline/minus.test
  tests/php/Integration/Fixtures/Inline/mod.test
  tests/php/Integration/Fixtures/Inline/mult.test
  tests/php/Integration/Fixtures/Inline/plus.test
  tests/php/Integration/Fixtures/Inline/pow.test
  tests/php/Integration/Fixtures/Inline/smaller-equal.test
  tests/php/Integration/Fixtures/Inline/smaller.test
  tests/php/Integration/Fixtures/Inline/spaceship.test
  tests/php/Integration/Fixtures/Inline/str.test
  tests/php/Unit/Compiler/Analyzer/SpecialForm/InvokeSymbolTest.php
Labels: enhancement

#428 Fixes the compile command when it rebuild using a cache.
  src/php/Build/Compile/ProjectCompiler.php
  src/php/Compiler/Analyzer/Environment/GlobalEnvironment.php
  src/php/Lang/Registry.php
  tests/php/Integration/Build/Command/CompileCommandTest.php
Labels: bug

#429 Use str_starts_with & str_contains instead of strpos
  src/phel/core.phel
  src/php/Command/Shared/Exceptions/Extractor/FilePositionExtractor.php
  src/php/Compiler/Parser/ExpressionParser/AtomParser.php
  src/php/Formatter/Domain/Rules/Indenter/LineIndenter.php
  src/php/Run/Domain/Repl/InputResult.php
Labels: refactoring

#430 Update gacela version
  composer.json
  composer.lock
  src/php/Build/BuildDependencyProvider.php
  src/php/Formatter/FormatterDependencyProvider.php
  src/php/Interop/InteropDependencyProvider.php
  src/php/Run/RunDependencyProvider.php
  tests/php/Integration/Compiler/Reader/ReaderTest.php
Labels: refactoring

#431 Fixes #410 Improve error handling in compile command
  src/php/Build/Command/CompileCommand.php
Labels: bug

#432 Add final dot to symbol doc
  src/phel/core.phel
  src/phel/html.phel
  src/phel/repl.phel
  src/phel/test.phel
  src/php/Compiler/Analyzer/Environment/GlobalEnvironment.php
  tests/php/Integration/Fixtures/Ns/munge-ns.test
Labels: documentation

#433 Updated Changelog.md
  Changelog.md
Labels: documentation
