Repository phel-lang/phel-lang, pull requests merged in 2022-03, with the labels that each got.

#451 Emit PHP array literals
  CHANGELOG.md
  src/php/Compiler/Analyzer/Analyzer.php
  src/php/Compiler/Emitter/OutputEmitter/LiteralEmitter.php
  tests/php/Integration/Fixtures/MacroExpand/return-array.test
  tests/php/Unit/Compiler/Analyzer/AnalyzeLiteralTest.php
Labels: enhancement

#452 Update Gacela to 0.14 version
  composer.json
  composer.lock
  phel
  src/php/Command/CommandConfig.php
  src/php/Command/CommandFactory.php
  src/php/Interop/InteropConfig.php
  src/php/Run/RunConfig.php
  tests/php/Integration/Printer/PrinterTest.php
Labels: dependencies

#453 Update gacela bootstrap in phel static helper
  src/php/Phel.php
  tests/php/Benchmark/Phel/PhelBench.php
Labels: bug

#454 Printer module using php80
  src/php/Printer/Printer.php
  src/php/Printer/PrinterInterface.php
  src/php/Printer/TypePrinter/AnonymousClassPrinter.php
  src/php/Printer/TypePrinter/ArrayPrinter.php
  src/php/Printer/TypePrinter/BooleanPrinter.php
  src/php/Printer/TypePrinter/FnPrinter.php
  src/php/Printer/TypePrinter/KeywordPrinter.php
  src/php/Printer/TypePrinter/NonPrintableClassPrinter.php
  src/php/Printer/TypePrinter/NullPrinter.php
  src/php/Printer/TypePrinter/NumberPrinter.php
  src/php/Printer/TypePrinter/ObjectPrinter.php
  src/php/Printer/TypePrinter/PersistentHashSetPrinter.php
  src/php/Printer/TypePrinter/PersistentListPrinter.php
  src/php/Printer/TypePrinter/PersistentMapPrinter.php
  src/php/Printer/TypePrinter/PersistentVectorPrinter.php
  src/php/Printer/TypePrinter/ResourcePrinter.php
  src/php/Printer/TypePrinter/StringPrinter.php
  src/php/Printer/TypePrinter/StructPrinter.php
  src/php/Printer/TypePrinter/SymbolPrinter.php
  src/php/Printer/TypePrinter/ToStringPrinter.php
  src/php/Printer/TypePrinter/TypePrinterInterface.php
Labels: bug, refactoring

#456 Update Gacela 0.15
  composer.json
  composer.lock
  phel
  src/php/Phel.php
Labels: enhancement
