Repository phel-lang/phel-lang, pull requests merged in 2022-11, with the labels that each got.

#533 Fixing broken tests
  tests/php/Integration/Formatter/FormatterFacadeTest.php
  tests/php/Integration/IntegrationTest.php
  tests/php/Integration/Interop/CallPhelTest.php
Labels: pure testing

#535 Add psalm/plugin-phpunit dependency
  composer.json
  composer.lock
  psalm.xml
Labels: dependencies

#534 Add execution time on compile command
  src/php/Build/Infrastructure/Command/CompileCommand.php
Labels: enhancement
