Repository phel-lang/phel-lang, pull requests merged in 2022-10, with the labels that each got.

#518 Update gacela@0.26
  composer.json
  composer.lock
  src/php/Phel.php
Labels: dependencies

#519 Inject FileIoInterface to FileCompiler and NamespaceExtractor
  src/php/Build/BuildFactory.php
  src/php/Build/Domain/Compile/FileCompiler.php
  src/php/Build/Domain/Extractor/NamespaceExtractor.php
  src/php/Build/Domain/IO/FileIoInterface.php
  src/php/Build/Infrastructure/Command/CompileCommand.php
  src/php/Build/Infrastructure/IO/SystemFileIo.php
  tests/php/Unit/Build/Extractor/NamespaceExtractorTest.php
Labels: refactoring

#522 Add argv argument to Phel::run()
  src/php/Phel.php
  tests/php/Integration/Phel/PhelTest.php
Labels: enhancement

#525 Format src and tests directories
  src/phel/core.phel
  src/phel/http.phel
  tests/phel/test/core/boolean-operation.phel
  tests/phel/test/core/for-loop.phel
  tests/phel/test/http.phel
Labels: refactoring

#520 Add contains-value? function
  src/phel/core.phel
  tests/phel/test/core/boolean-operation.phel
Labels: enhancement

#528 Update Gacela to 0.28 + dependencies
  composer.json
  composer.lock
  src/php/Lang/Collections/Map/PersistentHashMap.php
  src/php/Lang/Collections/Map/TransientHashMap.php
  tests/php/Integration/Run/Command/.gitignore
  tests/php/Integration/Run/Command/Repl.phel-repl-history
  tests/php/Integration/Run/Command/Repl/ReplCommandTest.php
  tests/php/Integration/Run/Command/Repl/ReplTestIo.php
Labels: dependencies

#527 Improve Phel documentation
  src/phel/core.phel
  src/phel/html.phel
  src/phel/http.phel
  src/phel/repl.phel
  src/phel/test.phel
Labels: documentation

#526 Refactoring FileCompiler and making CompileOptions optional
  src/phel/core.phel
  src/php/Build/Domain/Compile/FileCompiler.php
  src/php/Build/Domain/IO/FileIoInterface.php
  src/php/Build/Infrastructure/IO/SystemFileIo.php
  src/php/Compiler/CompilerFacade.php
  src/php/Compiler/Domain/Emitter/EmitterResult.php
  src/php/Compiler/Domain/Emitter/FileEmitter.php
  src/php/Compiler/Domain/Emitter/StatementEmitter.php
  tests/php/Integration/IntegrationTest.php
Labels: refactoring
