Repository phel-lang/phel-lang, pull requests merged in 2023-10, with the labels that each got.

#620 Update bumps
  .github/workflows/ci.yml
  .github/workflows/docker.yml
Labels: github_actions

#624 Define a custom registerDeprecatedHandler
  CHANGELOG.md
  src/php/Command/Domain/Handler/ExceptionHandler.php
Labels: enhancement

#629 Improve ExceptionHandler
  CHANGELOG.md
  src/php/Command/Domain/Handler/ExceptionHandler.php
  tests/php/Benchmark/Command/CommandBench.php
  tests/php/Benchmark/Command/fixtures/run-command.phel
Labels: enhancement

#633 Fix `phel repl` when not in the phel directory
  src/php/Build/Domain/Compile/DependenciesForNamespace.php
  src/php/Build/Domain/Extractor/NamespaceExtractor.php
  src/php/Command/CommandConfig.php
  src/php/Command/Domain/Finder/DirectoryFinder.php
  src/php/Run/Domain/Runner/NamespaceCollector.php
  tests/php/Integration/Build/Command/config/phel-config-no-namespace.php
  tests/php/Integration/Build/Command/config/phel-config.php
  tests/php/Integration/Interop/Command/Export/config/phel-config.php
Labels: bug

#634 Define custom --version
  bin/phel
Labels: enhancement
