Repository phel-lang/phel-lang, pull requests merged in 2023-02, with the labels that each got.

#562 Create test-numbers-with-underscore
  tests/phel/test/core/math-operation.phel
Labels: pure testing

#564 Allow underscores in decimal numbers
  CHANGELOG.md
  src/php/Compiler/Domain/Parser/ExpressionParser/AtomParser.php
  tests/phel/test/core/math-operation.phel
  tests/php/Unit/Compiler/Parser/ExpressionParser/AtomParserTest.php
Labels: enhancement

#565 ApiFacade returns a list of PhelFunctions
  adrs/php/0008_api_module.md
  composer.lock
  src/php/Api/ApiFacade.php
  src/php/Api/ApiFacadeInterface.php
  src/php/Api/Domain/PhelFnNormalizer.php
  src/php/Api/Domain/PhelFnNormalizerInterface.php
  src/php/Api/Infrastructure/Command/DocCommand.php
  src/php/Api/Transfer/PhelFunction.php
  tests/php/Integration/Api/ApiFacadeTest.php
  tests/php/Unit/Internal/Domain/PhelFnNormalizerTest.php
Labels: enhancement

#569 Add default format paths
  phel-config.php
  src/php/Formatter/FormatterConfig.php
  src/php/Formatter/Infrastructure/Command/FormatCommand.php
  tests/php/Integration/Formatter/Command/Format/FormatCommandTest.php
Labels: enhancement

#570 Rename compile-mode to build-mode
  CHANGELOG.md
  psalm.xml
  src/php/Build/Domain/Compile/FileCompiler.php
  src/php/Compiler/Domain/Analyzer/Environment/GlobalEnvironment.php
  src/php/Shared/BuildConstants.php
  src/php/Shared/CompilerConstants.php
  tests/php/Integration/Build/Command/src/hello.phel
  tests/php/Unit/Internal/Domain/PhelFnNormalizerTest.php
Labels: enhancement

#567 Add testdox option
  CHANGELOG.md
  src/phel/test.phel
  src/php/Run/Domain/Test/TestCommandOptions.php
  src/php/Run/Infrastructure/Command/TestCommand.php
  tests/php/Unit/Run/Domain/Test/TestCommandOptionsTest.php
Labels: enhancement

#572 Added fluent config
  CHANGELOG.md
  phel-config.php
  src/php/Config/PhelConfig.php
  src/php/Config/PhelExportConfig.php
  src/php/Interop/InteropConfig.php
  tests/php/Unit/Compiler/Config/PhelConfigTest.php
Labels: enhancement

#573 PhelConfig not accessible as array
  src/php/Command/Domain/Finder/ComposerVendorDirectoriesFinder.php
  src/php/Config/PhelConfigException.php
  tests/php/Integration/Command/Domain/DirectoryFinder/ComposerVendorDirectoriesFinderTest.php
  tests/php/Integration/Command/Domain/DirectoryFinder/testing-vendor/root-1/root-2/custom-src-2/hi.phel
  tests/php/Integration/Command/Domain/DirectoryFinder/testing-vendor/root-1/root-2/phel-config.php
  tests/php/Integration/Command/Domain/DirectoryFinder/testing-vendor/root-1/root-3/custom-src-3/hi.phel
  tests/php/Integration/Command/Domain/DirectoryFinder/testing-vendor/root-1/root-3/phel-config.php
  tests/php/Integration/Command/Domain/DirectoryFinder/wrong-testing-vendor/root-1/root-2/custom-src/hi.phel
  tests/php/Integration/Command/Domain/DirectoryFinder/wrong-testing-vendor/root-1/root-2/phel-config.php
Labels: bug

#574 Inject PhpConfigReader
  src/php/Command/CommandDependencyProvider.php
  src/php/Command/CommandFacade.php
  src/php/Command/CommandFacadeInterface.php
  src/php/Command/CommandFactory.php
  src/php/Command/Domain/Finder/ComposerVendorDirectoriesFinder.php
  src/php/Config/PhelConfigException.php
  tests/php/Integration/Command/Domain/DirectoryFinder/ComposerVendorDirectoriesFinderTest.php
  tests/php/Integration/Command/Domain/DirectoryFinder/wrong-testing-vendor/root-1/root-2/custom-src/hi.phel
  tests/php/Integration/Command/Domain/DirectoryFinder/wrong-testing-vendor/root-1/root-2/phel-config.php
Labels: refactoring

#576 Enable gacela cache by default
  .gitignore
  CHANGELOG.md
  src/php/Phel.php
Labels: enhancement

#575 Trigger a E_USER_NOTICE when finding a wrong phel config
  src/php/Command/CommandFacade.php
  src/php/Command/Domain/Finder/ComposerVendorDirectoriesFinder.php
  tests/php/Integration/Command/Domain/DirectoryFinder/ComposerVendorDirectoriesFinderTest.php
  tests/php/Integration/Command/Domain/DirectoryFinder/wrong-testing-vendor/root-1/root-2/phel-config.php
  tests/php/Integration/Command/Domain/DirectoryFinder/wrong-testing-vendor/root-1/root-3/custom-src-3/hi.phel
  tests/php/Integration/Command/Domain/DirectoryFinder/wrong-testing-vendor/root-1/root-3/phel-config.php
Labels: enhancement

#579 Fix apush, aset and aunset for global php arrays
  CHANGELOG.md
  src/php/Compiler/Domain/Analyzer/Ast/GlobalVarNode.php
  src/php/Compiler/Domain/Analyzer/Environment/NodeEnvironment.php
  src/php/Compiler/Domain/Analyzer/Environment/NodeEnvironmentInterface.php
  src/php/Compiler/Domain/Analyzer/TypeAnalyzer/SpecialForm/PhpAPushSymbol.php
  src/php/Compiler/Domain/Analyzer/TypeAnalyzer/SpecialForm/PhpASetSymbol.php
  src/php/Compiler/Domain/Analyzer/TypeAnalyzer/SpecialForm/PhpAUnsetSymbol.php
  src/php/Compiler/Domain/Emitter/OutputEmitter/NodeEmitter/GlobalVarEmitter.php
  src/php/Lang/Registry.php
  src/php/Run/Infrastructure/Command/ReplCommand.php
  tests/phel/test/core/sequence-operation.phel
  tests/php/Integration/Fixtures/Call/php-push-global-reference.test
  tests/php/Integration/Fixtures/Call/php-push.test
  tests/php/Unit/Lang/RegistryTest.php
Labels: bug

#582 CI not failing
  src/php/Console/Infrastructure/ConsoleBootstrap.php
Labels: bug

#581 Refactor NodeEnvironment
  src/php/Compiler/Domain/Analyzer/Ast/PhpVarNode.php
  src/php/Compiler/Domain/Analyzer/Environment/ContextualEnvironmentInterface.php
  src/php/Compiler/Domain/Analyzer/Environment/NodeEnvironment.php
  src/php/Compiler/Domain/Analyzer/Environment/NodeEnvironmentInterface.php
  src/php/Compiler/Domain/Analyzer/TypeAnalyzer/AnalyzePersistentMap.php
  src/php/Compiler/Domain/Analyzer/TypeAnalyzer/AnalyzePersistentVector.php
  src/php/Compiler/Domain/Analyzer/TypeAnalyzer/SpecialForm/ApplySymbol.php
  src/php/Compiler/Domain/Analyzer/TypeAnalyzer/SpecialForm/DefSymbol.php
  src/php/Compiler/Domain/Analyzer/TypeAnalyzer/SpecialForm/DoSymbol.php
  src/php/Compiler/Domain/Analyzer/TypeAnalyzer/SpecialForm/FnSymbol.php
  src/php/Compiler/Domain/Analyzer/TypeAnalyzer/SpecialForm/ForeachSymbol.php
  src/php/Compiler/Domain/Analyzer/TypeAnalyzer/SpecialForm/IfSymbol.php
  src/php/Compiler/Domain/Analyzer/TypeAnalyzer/SpecialForm/InvokeSymbol.php
  src/php/Compiler/Domain/Analyzer/TypeAnalyzer/SpecialForm/LetSymbol.php
  src/php/Compiler/Domain/Analyzer/TypeAnalyzer/SpecialForm/LoopSymbol.php
  src/php/Compiler/Domain/Analyzer/TypeAnalyzer/SpecialForm/PhpAGetSymbol.php
  src/php/Compiler/Domain/Analyzer/TypeAnalyzer/SpecialForm/PhpAPushSymbol.php
  src/php/Compiler/Domain/Analyzer/TypeAnalyzer/SpecialForm/PhpASetSymbol.php
  src/php/Compiler/Domain/Analyzer/TypeAnalyzer/SpecialForm/PhpAUnsetSymbol.php
  src/php/Compiler/Domain/Analyzer/TypeAnalyzer/SpecialForm/PhpNewSymbol.php
  src/php/Compiler/Domain/Analyzer/TypeAnalyzer/SpecialForm/PhpOSetSymbol.php
  src/php/Compiler/Domain/Analyzer/TypeAnalyzer/SpecialForm/PhpObjectCallSymbol.php
  src/php/Compiler/Domain/Analyzer/TypeAnalyzer/SpecialForm/RecurSymbol.php
  src/php/Compiler/Domain/Analyzer/TypeAnalyzer/SpecialForm/SetVarSymbol.php
  src/php/Compiler/Domain/Analyzer/TypeAnalyzer/SpecialForm/ThrowSymbol.php
  src/php/Compiler/Domain/Analyzer/TypeAnalyzer/SpecialForm/TrySymbol.php
  src/php/Compiler/Domain/Compiler/EvalCompiler.php
  src/php/Compiler/Domain/Emitter/OutputEmitter.php
  src/php/Compiler/Domain/Emitter/OutputEmitter/NodeEmitter/DoEmitter.php
  src/php/Compiler/Domain/Emitter/OutputEmitter/NodeEmitter/ForeachEmitter.php
  src/php/Compiler/Domain/Emitter/OutputEmitter/NodeEmitter/IfEmitter.php
  src/php/Compiler/Domain/Emitter/OutputEmitter/NodeEmitter/LetEmitter.php
  src/php/Compiler/Domain/Emitter/OutputEmitter/NodeEmitter/LiteralEmitter.php
  src/php/Compiler/Domain/Emitter/OutputEmitter/NodeEmitter/ThrowEmitter.php
  src/php/Compiler/Domain/Emitter/OutputEmitter/NodeEmitter/TryEmitter.php
  tests/php/Unit/Compiler/Analyzer/AnalyzePersistentListTest.php
  tests/php/Unit/Compiler/Analyzer/AnalyzePersistentMapTest.php
  tests/php/Unit/Compiler/Analyzer/AnalyzePersistentVectorTest.php
  tests/php/Unit/Compiler/Analyzer/SpecialForm/ApplySymbolTest.php
  tests/php/Unit/Compiler/Analyzer/SpecialForm/DefSymbolTest.php
  tests/php/Unit/Compiler/Analyzer/SpecialForm/ForeachSymbolTest.php
  tests/php/Unit/Compiler/Analyzer/SpecialForm/InvokeSymbolTest.php
  tests/php/Unit/Compiler/Analyzer/SpecialForm/LetSymbolTest.php
  tests/php/Unit/Compiler/Analyzer/SpecialForm/LoopSymbolTest.php
  tests/php/Unit/Compiler/Emitter/OutputEmitter/NodeEmitter/ApplyEmitterTest.php
Labels: refactoring
