Repository phel-lang/phel-lang, pull requests merged in 2023-01, with the labels that each got.

#547 Refactor phel/json tests
  CHANGELOG.md
  src/phel/json.phel
  tests/phel/test/json/decode/flags.phel
  tests/phel/test/json/decode/sample-value-2.json
  tests/phel/test/json/decode/value.phel
  tests/phel/test/json/encode/depth.phel
  tests/phel/test/json/encode/flags.phel
  tests/phel/test/json/encode/keys.phel
  tests/phel/test/json/encode/value.phel
Labels: refactoring

#548 Add phel test-struct-with-types
  tests/phel/test/core.phel
Labels: pure testing

#550 Fix docs for json functions
  src/phel/json.phel
Labels: bug

#551 Create Api module
  .gitignore
  CHANGELOG.md
  src/php/Api/ApiDependencyProvider.php
  src/php/Api/ApiFacade.php
  src/php/Api/ApiFacadeInterface.php
  src/php/Api/ApiFactory.php
  src/php/Api/Domain/PhelFnNormalizer.php
  src/php/Api/Domain/PhelFnNormalizerInterface.php
  src/php/Api/Infrastructure/PhelFnLoader.php
  src/php/Api/Infrastructure/PhelFnLoaderInterface.php
  src/php/Api/Infrastructure/phel/.gitkeep
  src/php/Api/Transfer/PhelFunction.php
  src/php/Run/RunFacadeInterface.php
  tests/php/Integration/Api/ApiFacadeTest.php
  tests/php/Integration/Api/config/phel-config.php
  tests/php/Unit/Internal/Domain/PhelFnNormalizerTest.php
Labels: enhancement

#555 Rename command compile to build
  CHANGELOG.md
  src/php/Build/Infrastructure/Command/BuildCommand.php
  src/php/Console/ConsoleDependencyProvider.php
  tests/php/Integration/Build/Command/BuildCommandTest.php
Labels: refactoring

#557 Allow ignore phel files when building the project
  CHANGELOG.md
  phel-config.php
  src/php/Build/BuildConfig.php
  src/php/Build/BuildFactory.php
  src/php/Build/Domain/Compile/ProjectCompiler.php
  src/php/Command/Domain/Shared/Exceptions/Extractor/SourceMapExtractor.php
  tests/php/Integration/Build/Command/config/phel-config.php
  tests/php/Integration/Build/Command/src/failing.phel
Labels: enhancement

#553 Remove generated temporal files
  CHANGELOG.md
  phel-config.php
  src/php/Compiler/CompilerDependencyProvider.php
  src/php/Compiler/CompilerFactory.php
  src/php/Compiler/Domain/Evaluator/RequireEvaluator.php
  src/php/Console/ConsoleDependencyProvider.php
  src/php/Console/ConsoleFactory.php
  src/php/Console/Infrastructure/ConsoleBootstrap.php
  src/php/Filesystem/Domain/FilesystemInterface.php
  src/php/Filesystem/Domain/NullFilesystem.php
  src/php/Filesystem/FilesystemConfig.php
  src/php/Filesystem/FilesystemFacade.php
  src/php/Filesystem/FilesystemFacadeInterface.php
  src/php/Filesystem/FilesystemFactory.php
  src/php/Filesystem/Infrastructure/RealFilesystem.php
  tests/php/Integration/Filesystem/FilesystemFacadeTest.php
Labels: enhancement

#552 Create DocCommand
  CHANGELOG.md
  src/php/Api/Infrastructure/Command/DocCommand.php
  src/php/Console/ConsoleDependencyProvider.php
Labels: enhancement

#558 Refactor Hasher
  src/php/Lang/Hasher.php
Labels: refactoring

#559 Replace switch by match in Parser->readExpression()
  src/php/Compiler/Domain/Parser/Parser.php
Labels: enhancement
