Repository phel-lang/phel-lang, pull requests merged in 2024-04, with the labels that each got.

#680 Update composer dependencies
  composer.lock
  src/php/Build/Domain/Extractor/NamespaceExtractor.php
Labels: dependencies

#683 Add support for numeric on empty?
  .editorconfig
  CHANGELOG.md
  src/phel/core.phel
  tests/phel/test/core/math-operation.phel
  tests/phel/test/core/type-operation.phel
Labels: enhancement

#682 Fix interleave with nil values
  CHANGELOG.md
  src/phel/core.phel
  tests/phel/test/core/sequence-functions.phel
Labels: bug

#685 Add NoCacheWhenBuilding setting
  CHANGELOG.md
  phel-config.php
  src/php/Build/BuildConfig.php
  src/php/Build/BuildConfigInterface.php
  src/php/Build/BuildFactory.php
  src/php/Build/Domain/Compile/ProjectCompiler.php
  src/php/Config/PhelConfig.php
  tests/php/Integration/Build/Command/BuildCommandTest.php
  tests/php/Integration/Build/Command/config/phel-config.php
  tests/php/Integration/Build/Command/src/hello.phel
  tests/php/Integration/Build/Command/src/no-cache.phel
  tests/php/Unit/Compiler/Config/PhelConfigTest.php
Labels: enhancement

#686 fix: BuildMode when transpiling the code
  src/php/Build/BuildFacade.php
  src/php/Build/Domain/Compile/FileCompiler.php
  src/php/Build/Domain/Compile/ProjectCompiler.php
  src/php/Compiler/Domain/Analyzer/Environment/GlobalEnvironment.php
Labels: bug

#688 feat: add string functions.
  CHANGELOG.md
  src/phel/str.phel
  tests/phel/test/str.phel
Labels: enhancement
