Repository phel-lang/phel-lang, pull requests merged in 2024-08, with the labels that each got.

#747 Fix `some?` function for an empty vector
  CHANGELOG.md
  src/phel/core.phel
  tests/phel/test/core/boolean-operation.phel
  tests/phel/test/core/sequence-functions.phel
Labels: bug

#749 Fix `binding` function for atom body
  CHANGELOG.md
  src/phel/core.phel
  tests/phel/test/core/binding.phel
Labels: bug

#740 Added: Tests to proof documentations.
  tests/phel/test/special-forms.phel
Labels: pure testing

#751 Upgrade code style fixer
  composer.json
  composer.lock
  src/php/Api/Infrastructure/PhelFnLoader.php
  src/php/Build/Application/ProjectCompiler.php
  src/php/Build/Domain/Compile/Output/EntryPointPhpFile.php
  src/php/Build/Infrastructure/Command/BuildCommand.php
  src/php/Command/Domain/Exceptions/ExceptionArgsPrinter.php
  src/php/Command/Infrastructure/ComposerVendorDirectoriesFinder.php
  src/php/Command/Infrastructure/ExceptionHandler.php
  src/php/Compiler/Domain/Analyzer/Exceptions/AnalyzerException.php
  src/php/Compiler/Domain/Analyzer/TypeAnalyzer/AnalyzeSymbol.php
  src/php/Compiler/Domain/Analyzer/TypeAnalyzer/SpecialForm/Binding/Deconstructor/VectorBindingDeconstructor.php
  src/php/Compiler/Domain/Analyzer/TypeAnalyzer/SpecialForm/NsSymbol.php
  src/php/Compiler/Domain/Analyzer/TypeAnalyzer/SpecialForm/PhpObjectCallSymbol.php
  src/php/Compiler/Domain/Emitter/Exceptions/NotSupportedAstException.php
  src/php/Compiler/Domain/Lexer/Exceptions/LexerValueException.php
  src/php/Compiler/Domain/Parser/ExpressionParser/AtomParser.php
  src/php/Config/PhelBuildConfig.php
  src/php/Formatter/Domain/Exception/FilePathException.php
  src/php/Formatter/Infrastructure/Command/FormatCommand.php
  src/php/Interop/Infrastructure/Command/ExportCommand.php
  src/php/Interop/Infrastructure/Io/FileSystemIo.php
  src/php/Lang/Collections/Struct/AbstractPersistentStruct.php
  src/php/Lang/Collections/Vector/PersistentVector.php
  src/php/Lang/Collections/Vector/SubVector.php
  src/php/Printer/TypePrinter/ArrayPrinter.php
  src/php/Printer/TypePrinter/BooleanPrinter.php
  src/php/Printer/TypePrinter/KeywordPrinter.php
  src/php/Printer/TypePrinter/NonPrintableClassPrinter.php
  src/php/Printer/TypePrinter/NullPrinter.php
  src/php/Printer/TypePrinter/NumberPrinter.php
  src/php/Printer/TypePrinter/StringPrinter.php
  src/php/Printer/TypePrinter/SymbolPrinter.php
  src/php/Run/Domain/Repl/ColorStyle.php
  src/php/Run/Domain/Repl/InputResult.php
  src/php/Run/Domain/Repl/MissingDependencyException.php
  src/php/Run/Infrastructure/Command/ReplCommand.php
  src/php/Run/Infrastructure/Command/TestCommand.php
  tests/php/Integration/Compiler/Parser/ParserTest.php
  tests/php/Integration/Compiler/Reader/ReaderTest.php
  tests/php/Unit/Run/Domain/Repl/ColorStyleTest.php
Labels: dependencies

#752 Upgrade gacela 1.8
  composer.json
  composer.lock
  src/php/Api/ApiFactory.php
  src/php/Api/ApiProvider.php
  src/php/Build/BuildFactory.php
  src/php/Build/BuildProvider.php
  src/php/Command/CommandFactory.php
  src/php/Command/CommandProvider.php
  src/php/Compiler/CompilerFactory.php
  src/php/Compiler/CompilerProvider.php
  src/php/Console/ConsoleFactory.php
  src/php/Console/ConsoleProvider.php
  src/php/Formatter/FormatterFactory.php
  src/php/Formatter/FormatterProvider.php
  src/php/Interop/InteropFactory.php
  src/php/Interop/InteropProvider.php
  src/php/Run/RunFactory.php
  src/php/Run/RunProvider.php
  tests/php/Integration/Run/Command/Repl/ReplCommandTest.php
Labels: enhancement
