Repository phel-lang/phel-lang, pull requests merged in 2024-05, with the labels that each got.

#690 Remove output from tests
  tests/php/Integration/Api/ApiFacadeTest.php
  tests/php/Integration/Build/Command/BuildCommandTest.php
Labels: refactoring

#695 Fix $ as named parameter in macros
  CHANGELOG.md
  src/php/Compiler/Infrastructure/Munge.php
  tests/phel/test/core/threading-macros.phel
Labels: bug

#696 Rename PhelOutConfig to PhelBuildConfig
  CHANGELOG.md
  phel-config.php
  src/php/Build/BuildConfig.php
  src/php/Build/BuildFactory.php
  src/php/Build/Domain/Compile/Output/EntryPointPhpFile.php
  src/php/Command/CommandConfig.php
  src/php/Command/Domain/Finder/ComposerVendorDirectoriesFinder.php
  src/php/Config/PhelBuildConfig.php
  src/php/Config/PhelConfig.php
  src/php/Config/PhelExportConfig.php
  src/php/Filesystem/FilesystemConfig.php
  src/php/Formatter/FormatterConfig.php
  src/php/Interop/InteropConfig.php
  tests/php/Integration/Build/Command/config/phel-config-no-namespace.php
  tests/php/Integration/Build/Command/config/phel-config.php
  tests/php/Integration/Command/Domain/DirectoryFinder/testing-vendor/root-1/root-2/phel-config.php
  tests/php/Integration/Filesystem/FilesystemFacadeTest.php
  tests/php/Integration/Formatter/Command/Format/FormatCommandTest.php
  tests/php/Unit/Compiler/Config/PhelBuildConfigTest.php
  tests/php/Unit/Compiler/Config/PhelConfigTest.php
  tests/php/Unit/Compiler/Config/PhelOutConfigTest.php
Labels: refactoring

#698 Fix avoid using trim on PhelBuildConfig
  CHANGELOG.md
  src/php/Config/PhelBuildConfig.php
  tests/php/Unit/Compiler/Config/PhelBuildConfigTest.php
Labels: bug

#699 Change default config dirs
  CHANGELOG.md
  src/php/Config/PhelConfig.php
  src/php/Config/PhelExportConfig.php
  tests/php/Unit/Compiler/Config/PhelConfigTest.php
Labels: enhancement

#701 fix: restore pre-refactor behaviour
  bin/phel
Labels: bug
