Repository phel-lang/phel-lang, pull requests merged in 2024-06, with the labels that each got.

#712 fix: check for readline extension in REPL
  CHANGELOG.md
  src/php/Run/Domain/Repl/MissingDependencyException.php
  src/php/Run/Domain/Repl/ReplCommandSystemIo.php
Labels: bug

#711 Remove unnecessary condition in ReplCommandTest
  tests/php/Integration/Run/Command/Repl/ReplCommandTest.php
Labels: refactoring

#715 Flaky ExportCommandTest
  .php-cs-fixer.dist.php
  tests/php/Integration/Interop/Command/Export/ExportCommandTest.php
Labels: bug

#718 fix: deprecation notice for signed hexadecimals
  phpunit.xml.dist
  src/php/Compiler/Domain/Parser/ExpressionParser/AtomParser.php
  tests/php/Unit/Compiler/Parser/ExpressionParser/AtomParserTest.php
Labels: bug

#714 Compatibility of lists and vectors in the cons function
  CHANGELOG.md
  src/php/Lang/Collections/Vector/PersistentVector.php
  src/php/Lang/Collections/Vector/PersistentVectorInterface.php
  src/php/Lang/Collections/Vector/SubVector.php
  tests/phel/test/core/basic-sequence-operation.phel
Labels: enhancement

#717 feat: Check mandatory function parameters during compile time.
  CHANGELOG.md
  src/php/Compiler/Domain/Analyzer/Ast/FnNode.php
  src/php/Compiler/Domain/Analyzer/Exceptions/AnalyzerException.php
  src/php/Compiler/Domain/Analyzer/TypeAnalyzer/SpecialForm/DefSymbol.php
  src/php/Compiler/Domain/Analyzer/TypeAnalyzer/SpecialForm/InvokeSymbol.php
  tests/php/Integration/Fixtures/Call/global-call.test
  tests/php/Integration/Fixtures/Call/php-fn-reference.test
  tests/php/Integration/Fixtures/Def/definterface-instance-of.test
  tests/php/Integration/Fixtures/Def/definterface.test
  tests/php/Integration/Fixtures/Def/defn-meta.test
  tests/php/Integration/Fixtures/Foreach/foreach-expr.test
  tests/php/Integration/Fixtures/MacroExpand/macro-expand.test
  tests/php/Integration/Fixtures/MacroExpand/return-array.test
  tests/php/Integration/Fixtures/Ns/munge-ns.test
  tests/php/Integration/Fixtures/Try/throw-expr.test
  tests/php/Unit/Compiler/Analyzer/SpecialForm/InvokeSymbolTest.php
Labels: enhancement

#720 Improve output for doc command
  CHANGELOG.md
  src/php/Api/Infrastructure/Command/DocCommand.php
Labels: enhancement

#722 Fix doc command
  src/php/Api/Infrastructure/Command/DocCommand.php
Labels: bug

#727 Fix recursive private access
  CHANGELOG.md
  src/php/Compiler/Application/Analyzer.php
  src/php/Compiler/Domain/Analyzer/Environment/GlobalEnvironment.php
  src/php/Compiler/Domain/Analyzer/Environment/GlobalEnvironmentInterface.php
  tests/phel/test/core/control-structures.phel
Labels: bug
