Repository phel-lang/phel-lang, pull requests merged in 2025-09, with the labels that each got.

#934 Allow passing cli flags args to phel run scripts
  CHANGELOG.md
  src/php/Console/Application/ArgvInputSanitizer.php
  src/php/Console/ConsoleFactory.php
  src/php/Console/Infrastructure/ConsoleBootstrap.php
  tests/php/Integration/Run/Command/Run/Fixtures/argv-script.phel
  tests/php/Integration/Run/Command/Run/RunTestCommand.php
Labels: bug

#941 Add docUrl and fnNs to PhelFunction
  src/php/Api/Application/PhelFnNormalizer.php
  src/php/Api/Domain/PhelFnLoaderInterface.php
  src/php/Api/Infrastructure/Command/DocCommand.php
  src/php/Api/Infrastructure/PhelFnLoader.php
  src/php/Api/Transfer/PhelFunction.php
  tests/php/Unit/Internal/Domain/PhelFnNormalizerTest.php
Labels: enhancement

#943 Add rawDoc to PhelFunction
  CHANGELOG.md
  src/php/Api/Application/PhelFnNormalizer.php
  src/php/Api/Application/ReplCompleter.php
  src/php/Api/Domain/PhelFnLoaderInterface.php
  src/php/Api/Infrastructure/PhelFnLoader.php
  src/php/Api/Transfer/PhelFunction.php
  tests/php/Unit/Internal/Domain/PhelFnNormalizerTest.php
Labels: enhancement

#949 Deprecate PhelFunction methods in favor of public props
  CHANGELOG.md
  src/php/Api/Application/PhelFnNormalizer.php
  src/php/Api/Infrastructure/Command/DocCommand.php
  src/php/Api/Transfer/PhelFunction.php
  tests/php/Unit/Internal/Domain/PhelFnNormalizerTest.php
Labels: enhancement

#952 Fix meta on definitions
  CHANGELOG.md
  src/phel/core.phel
  tests/phel/test/core/meta.phel
Labels: bug

#953 Add meta to PhelFunction
  CHANGELOG.md
  src/php/Api/Application/PhelFnNormalizer.php
  src/php/Api/Transfer/PhelFunction.php
  src/php/Formatter/Domain/Rules/IndentRule.php
  src/php/Formatter/Domain/Rules/Indenter/ListIndenter.php
  tests/php/Unit/Internal/Domain/PhelFnNormalizerTest.php
Labels: enhancement

#958 Add comma separator between key value pairs in the hash-map printer
  CHANGELOG.md
  src/php/Printer/TypePrinter/PersistentMapPrinter.php
  src/php/Run/Domain/Test/TestCommandOptions.php
  tests/php/Unit/Printer/TypePrinter/PersistentMapPrinterTest.php
Labels: enhancement

#960 Add "into" core function
  CHANGELOG.md
  src/phel/core.phel
  tests/phel/test/core/sequence-functions.phel
  tests/php/Integration/Api/ApiFacadeTest.php
Labels: enhancement

#966 `argv` as Phel vector instead of PHP array
  src/phel/core.phel
Labels: enhancement

#968 Use custom if-throw for pre/post metadata conditions
  .github/workflows/ci.yml
  CHANGELOG.md
  src/php/Compiler/Domain/Analyzer/TypeAnalyzer/SpecialForm/FnSymbol.php
  tests/phel/test/core/pre-post-conditions.phel
Labels: enhancement

#972 Allow disabling meta conditions to improve performance
  CHANGELOG.md
  phel-config.php
  src/php/Compiler/Application/Analyzer.php
  src/php/Compiler/CompilerConfig.php
  src/php/Compiler/CompilerFactory.php
  src/php/Compiler/Domain/Analyzer/TypeAnalyzer/AnalyzePersistentList.php
  src/php/Compiler/Domain/Analyzer/TypeAnalyzer/SpecialForm/FnSymbol.php
  src/php/Compiler/Domain/Analyzer/TypeAnalyzer/WithAnalyzerTrait.php
  src/php/Config/PhelConfig.php
  tests/php/Unit/Compiler/Analyzer/AnalyzePersistentListTest.php
  tests/php/Unit/Compiler/Analyzer/SpecialForm/FnSymbolTest.php
  tests/php/Unit/Compiler/Config/PhelConfigTest.php
Labels: enhancement

#974 Increase PHPStan level to 4
  CHANGELOG.md
  phpstan.neon
  src/Phel.php
  src/php/Api/Application/PhelFnNormalizer.php
  src/php/Api/Application/ReplCompleter.php
  src/php/Api/Domain/PhelFnLoaderInterface.php
  src/php/Api/Infrastructure/PhelFnLoader.php
  src/php/Command/Application/TextExceptionPrinter.php
  src/php/Command/Domain/Exceptions/Extractor/FilePositionExtractor.php
  src/php/Compiler/Domain/Analyzer/TypeAnalyzer/SpecialForm/ReadModel/FnSymbolTuple.php
  src/php/Compiler/Domain/Emitter/OutputEmitter/NodeEmitter/RecurEmitter.php
  src/php/Compiler/Domain/Reader/ExpressionReader/ListFnReader.php
  src/php/Filesystem/Application/TempDirFinder.php
  src/php/Formatter/Domain/Rules/Zipper/AbstractZipper.php
  src/php/Interop/PhelCaller.php
  src/php/Lang/Generators.php
  src/php/Lang/Keyword.php
  src/php/Run/Infrastructure/Command/DoctorCommand.php
Labels: refactoring

#975 Increase PHPStan level to 5
  CHANGELOG.md
  phpstan.neon
  src/Phel.php
  src/php/Build/Application/NamespaceExtractor.php
  src/php/Formatter/Domain/Rules/RemoveSurroundingWhitespaceRule.php
  src/php/Formatter/Domain/Rules/RemoveTrailingWhitespaceRule.php
  src/php/Formatter/Domain/Rules/UnindentRule.php
Labels: refactoring

#985 Add format json to doc command
  CHANGELOG.md
  src/php/Api/Infrastructure/Command/DocCommand.php
Labels: enhancement

#986 Fix doc command on phar
  CHANGELOG.md
  src/php/Api/Infrastructure/PhelFnLoader.php
  src/php/Build/Application/NamespaceExtractor.php
Labels: bug
