Repository phel-lang/phel-lang, pull requests merged in 2025-05, with the labels that each got.

#799 fix: Fix Hash-map malfunction notice #786
  CHANGELOG.md
  src/php/Lang/Collections/Map/ArrayNode.php
  tests/phel/test/core.phel
Labels: bug

#805 Improve string case functions
  CHANGELOG.md
  src/phel/str.phel
  tests/phel/test/str.phel
Labels: enhancement, codex

#806 Strings in output should be wrapped with quotes
  CHANGELOG.md
  src/phel/repl.phel
  src/php/Printer/Printer.php
  src/php/Run/RunFactory.php
  tests/php/Integration/Printer/PrinterTest.php
Labels: enhancement

#807 Fix null checks on Analyzer forms
  CHANGELOG.md
  src/php/Compiler/Domain/Analyzer/TypeAnalyzer/SpecialForm/DefStructSymbol.php
  src/php/Compiler/Domain/Analyzer/TypeAnalyzer/SpecialForm/DoSymbol.php
  src/php/Compiler/Domain/Analyzer/TypeAnalyzer/SpecialForm/NsSymbol.php
  src/php/Compiler/Domain/Analyzer/TypeAnalyzer/SpecialForm/PhpNewSymbol.php
  src/php/Compiler/Domain/Analyzer/TypeAnalyzer/SpecialForm/PhpObjectCallSymbol.php
  src/php/Compiler/Domain/Analyzer/TypeAnalyzer/SpecialForm/RecurSymbol.php
  src/php/Lang/Collections/LinkedList/PersistentList.php
  src/php/Lang/Collections/Vector/AbstractPersistentVector.php
  src/php/Lang/Collections/Vector/SubVector.php
Labels: bug, codex

#809 Optimize vector iteration
  src/php/Lang/Collections/Vector/RangeIterator.php
Labels: enhancement, codex

#810 Add macroexpand functions
  CHANGELOG.md
  src/phel/core.phel
  tests/phel/test/core/macroexpand.phel
  tests/php/Integration/Api/ApiFacadeTest.php
Labels: enhancement, codex

#813 Fix private symbol refer resolution
  CHANGELOG.md
  src/php/Compiler/Domain/Analyzer/Environment/GlobalEnvironment.php
  tests/php/Unit/Compiler/Analyzer/Environment/GlobalEnvironmentTest.php
Labels: bug, codex

#815 Fix allow re-def bindings on REPL
  src/php/Compiler/Domain/Analyzer/Environment/GlobalEnvironment.php
  src/php/Run/Infrastructure/Command/ReplCommand.php
  src/php/Shared/ReplConstants.php
  tests/php/Integration/Run/Command/Repl/Fixtures/redef.test
Labels: bug

#819 Implement defexception special form
  CHANGELOG.md
  src/phel/core.phel
  src/php/Api/Infrastructure/PhelFnLoader.php
  src/php/Compiler/Domain/Analyzer/Ast/DefExceptionNode.php
  src/php/Compiler/Domain/Analyzer/TypeAnalyzer/AnalyzePersistentList.php
  src/php/Compiler/Domain/Analyzer/TypeAnalyzer/SpecialForm/DefExceptionSymbol.php
  src/php/Compiler/Domain/Emitter/OutputEmitter/NodeEmitter/DefExceptionEmitter.php
  src/php/Compiler/Domain/Emitter/OutputEmitter/NodeEmitterFactory.php
  src/php/Lang/Symbol.php
  tests/php/Integration/Api/ApiFacadeTest.php
  tests/php/Integration/Fixtures/Def/defexception.test
  tests/php/Unit/Compiler/Analyzer/AnalyzePersistentListTest.php
  tests/php/Unit/Compiler/Analyzer/SpecialForm/DefExceptionSymbolTest.php
Labels: enhancement, codex

#820 Fix REPL ns evaluation
  CHANGELOG.md
  src/php/Compiler/Domain/Analyzer/TypeAnalyzer/SpecialForm/NsSymbol.php
  src/php/Compiler/Domain/Emitter/OutputEmitter/NodeEmitter/NsEmitter.php
Labels: bug, codex

#821 Add REPL completion
  CHANGELOG.md
  src/php/Run/Domain/Repl/ReplCommandSystemIo.php
Labels: enhancement

#823 Improve vector performance
  CHANGELOG.md
  src/php/Lang/Collections/Vector/PersistentVector.php
  src/php/Lang/Collections/Vector/TransientVector.php
Labels: refactoring, codex

#824 Resolve macros in ns that contain hyphens
  src/php/Compiler/Domain/Analyzer/Environment/GlobalEnvironment.php
  tests/php/Unit/Compiler/Analyzer/Environment/GlobalEnvironmentTest.php
Labels: bug, codex

#829 Add recursive PHP-Phel conversion functions
  CHANGELOG.md
  src/phel/core.phel
  tests/phel/test/core/sequence-functions.phel
  tests/php/Integration/Api/ApiFacadeTest.php
Labels: codex

#828 Fix macroExpand to encode ns by replacing hyphens with underscores
  src/php/Compiler/Domain/Analyzer/TypeAnalyzer/SpecialForm/InvokeSymbol.php
  tests/php/Unit/Compiler/Analyzer/SpecialForm/InvokeSymbolTest.php
Labels: bug

#832 Fix cannot reload user ns
  CHANGELOG.md
  src/php/Compiler/Domain/Emitter/OutputEmitter/NodeEmitter/DefStructEmitter.php
  tests/php/Integration/Fixtures/Def/defstruct-interface-without-methods.test
  tests/php/Integration/Fixtures/Def/defstruct-one-interface.test
  tests/php/Integration/Fixtures/Def/defstruct-two-interfaces.test
  tests/php/Integration/Fixtures/Def/defstruct.test
  tests/php/Integration/Fixtures/Ns/munge-ns.test
Labels: bug
