Repository phel-lang/phel-lang, pull requests merged in 2025-08, with the labels that each got.

#857 Fix repl prints unicode chars
  CHANGELOG.md
  src/php/Printer/TypePrinter/StringPrinter.php
  tests/php/Integration/Printer/PrinterTest.php
  tests/php/Unit/Printer/TypePrinter/StringPrinterTest.php
Labels: bug

#863 Fix require broke in repl
  CHANGELOG.md
  src/php/Build/Application/DependenciesForNamespace.php
Labels: bug

#864 Fix trigger warning in RequireEvaluatorTest
  CHANGELOG.md
  tests/php/Integration/Compiler/Evaluator/RequireEvaluatorTest.php
Labels: bug, pure testing

#870 Add more repl tests
  tests/php/Integration/Run/Command/Repl/Fixtures/multiline-let.test
  tests/php/Integration/Run/Command/Repl/FixturesWithCoreLib/render-function-reference.test
  tests/php/Integration/Run/Command/Repl/FixturesWithCoreLib/render-ns-name-after-required.test
  tests/php/Integration/Run/Command/Repl/FixturesWithCoreLib/require-namespace.test
  tests/php/Integration/Run/Command/Repl/FixturesWithCoreLib/use-namespace.test
Labels: pure testing

#875 Fix `map` function exhaustion with empty collections
  CHANGELOG.md
  src/phel/core.phel
  tests/phel/test/core/sequence-functions.phel
Labels: bug

#878 feat: add `select-keys` function
  CHANGELOG.md
  src/phel/core.phel
  tests/phel/test/core/sequence-functions.phel
  tests/php/Integration/Api/ApiFacadeTest.php
Labels: enhancement

#883 Fix set difference errors with certain input
  CHANGELOG.md
  src/php/Lang/Collections/Map/ArrayNodeIterator.php
  tests/php/Unit/Lang/Collections/Map/ArrayNodeIteratorTest.php
Labels: bug

#892 Refactor phpcs with more rules
  .php-cs-fixer.dist.php
  src/php/Api/Application/PhelFnNormalizer.php
  src/php/Api/Application/ReplCompleter.php
  src/php/Api/Infrastructure/PhelFnLoader.php
  src/php/Build/Application/NamespaceExtractor.php
  src/php/Build/BuildFacade.php
  src/php/Build/BuildFacadeInterface.php
  src/php/Build/Domain/Extractor/NamespaceSorterInterface.php
  src/php/Build/Domain/Extractor/TopologicalNamespaceSorter.php
  src/php/Compiler/CompilerFacadeInterface.php
  src/php/Compiler/Domain/Analyzer/Ast/DefStructNode.php
  src/php/Compiler/Domain/Analyzer/Environment/GlobalEnvironment.php
  src/php/Compiler/Domain/Analyzer/Environment/NodeEnvironment.php
  src/php/Compiler/Domain/Analyzer/TypeAnalyzer/AnalyzePersistentList.php
  src/php/Compiler/Domain/Analyzer/TypeAnalyzer/AnalyzePersistentMap.php
  src/php/Compiler/Domain/Analyzer/TypeAnalyzer/AnalyzePersistentVector.php
  src/php/Compiler/Domain/Analyzer/TypeAnalyzer/SpecialForm/Binding/Deconstructor.php
  src/php/Compiler/Domain/Analyzer/TypeAnalyzer/SpecialForm/Binding/Deconstructor/BindingDeconstructorInterface.php
  src/php/Compiler/Domain/Analyzer/TypeAnalyzer/SpecialForm/Binding/Deconstructor/MapBindingDeconstructor.php
  src/php/Compiler/Domain/Analyzer/TypeAnalyzer/SpecialForm/Binding/Deconstructor/SymbolBindingDeconstructor.php
  src/php/Compiler/Domain/Compiler/CodeCompilerInterface.php
  src/php/Compiler/Domain/Compiler/EvalCompilerInterface.php
  src/php/Compiler/Domain/Parser/ParserNode/AbstractAtomNode.php
  src/php/Compiler/Domain/Parser/ParserNode/NumberNode.php
  src/php/Compiler/Domain/Reader/QuasiquoteTransformer.php
  src/php/Compiler/Domain/Reader/QuasiquoteTransformerInterface.php
  src/php/Config/PhelConfig.php
  src/php/Formatter/Domain/Rules/Zipper/AbstractZipper.php
  src/php/Formatter/Domain/Rules/Zipper/ParseTreeZipper.php
  src/php/Lang/Collections/LinkedList/PersistentList.php
  src/php/Lang/Collections/Map/HashMapNodeInterface.php
  src/php/Lang/Collections/Map/IndexedNode.php
  src/php/Lang/Collections/Map/IndexedNodeIterator.php
  src/php/Lang/Collections/Map/PersistentHashMap.php
  src/php/Lang/Collections/Map/TransientHashMap.php
  src/php/Lang/Collections/Vector/AbstractPersistentVector.php
  src/php/Lang/Collections/Vector/PersistentVector.php
  src/php/Lang/Collections/Vector/TransientVector.php
  src/php/Lang/ConsInterface.php
  src/php/Lang/PushInterface.php
  src/php/Lang/RemoveInterface.php
  src/php/Lang/SliceInterface.php
  src/php/Phel.php
  src/php/Printer/TypePrinter/NumberPrinter.php
  src/php/Run/Infrastructure/Command/TestCommand.php
  src/php/Run/RunFacadeInterface.php
  tests/php/Unit/Formatter/Domain/Rules/Zipper/ArrayZipper.php
Labels: refactoring

#895 Fix require ns loading code without build-mode
  CHANGELOG.md
  src/php/Compiler/Domain/Emitter/OutputEmitter/NodeEmitter/NsEmitter.php
  tests/php/Integration/Run/RequireBuildMode/Fixtures/example/game.phel
  tests/php/Integration/Run/RequireBuildMode/Fixtures/example/main.phel
  tests/php/Integration/Run/RequireBuildMode/RequireBuildModeTest.php
Labels: bug

#898 Test ThrowSymbol
  tests/php/Unit/Compiler/Analyzer/SpecialForm/ThrowSymbolTest.php
Labels: pure testing

#899 Add Clojure-style aliases for assoc and dissoc
  CHANGELOG.md
  src/phel/core.phel
  tests/phel/test/core/sequence-functions.phel
  tests/phel/test/core/sequence-operation.phel
  tests/php/Integration/Api/ApiFacadeTest.php
Labels: enhancement

#900 Add iterate to core and extend take to handle generators
  CHANGELOG.md
  src/phel/core.phel
  tests/phel/test/core/sequence-functions.phel
  tests/php/Integration/Api/ApiFacadeTest.php
Labels: enhancement

#901 Combine reduce and reduce2
  CHANGELOG.md
  src/phel/core.phel
  tests/phel/test/core/sequence-functions.phel
  tests/php/Integration/Api/ApiFacadeTest.php
Labels: enhancement

#913 Fix REPL symbol resolution issue loading current dir
  CHANGELOG.md
  src/php/Run/Infrastructure/Command/ReplCommand.php
  tests/php/Integration/Run/Command/Repl/Fixtures/require-current-dir.test
  tests/php/Integration/Run/Command/Repl/ReplTestCommand.php
  tests/php/Integration/Run/Command/Repl/util.phel
Labels: bug

#917 Add map destructuring with keys and as
  CHANGELOG.md
  src/php/Compiler/Domain/Analyzer/TypeAnalyzer/SpecialForm/Binding/Deconstructor/MapBindingDeconstructor.php
  tests/phel/test/core.phel
  tests/php/Unit/Compiler/Analyzer/SpecialForm/Binding/Deconstructor/MapBindingDeconstructorTest.php
Labels: enhancement

#915 Add ; as alternative comment symbol
  CHANGELOG.md
  src/php/Compiler/Application/Lexer.php
  tests/php/Integration/Compiler/Parser/ParserTest.php
  tests/php/Unit/Compiler/Lexer/LexerTest.php
Labels: enhancement

#918 Show current phel repl version
  .github/RELEASE.md
  CHANGELOG.md
  bin/phel
  src/php/Console/Application/VersionFinder.php
  src/php/Console/ConsoleFacade.php
  src/php/Console/ConsoleFacadeInterface.php
  src/php/Console/ConsoleFactory.php
  src/php/Console/ConsoleProvider.php
  src/php/Run/Infrastructure/Command/ReplCommand.php
  src/php/Run/RunFacade.php
  src/php/Run/RunFacadeInterface.php
  src/php/Run/RunFactory.php
  src/php/Run/RunProvider.php
  tests/php/Unit/Console/Application/VersionFinderTest.php
Labels: enhancement

#924 Fix func metadata parsing conflict with literal hashmap
  CHANGELOG.md
  src/php/Compiler/Domain/Analyzer/TypeAnalyzer/SpecialForm/FnSymbol.php
  tests/phel/test/core/fn-map-body.phel
Labels: bug

#928 Update default error log file
  CHANGELOG.md
  src/php/Command/CommandConfig.php
Labels: enhancement

#930 Add macro auto-gensym syntax
  CHANGELOG.md
  src/phel/core.phel
  src/php/Compiler/Domain/Reader/GensymContext.php
  src/php/Compiler/Domain/Reader/QuasiquoteTransformer.php
  tests/php/Integration/Compiler/Reader/ReaderTest.php
Labels: enhancement
